// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AgentExecutionConfig struct {
	WorkMode *AgentWorkMode         `json:"workMode,omitempty"`
	Codex    *CodexExecutionConfig  `json:"codex,omitempty"`
	Claude   *ClaudeExecutionConfig `json:"claude,omitempty"`
}

type AgentExecutionConfigInput struct {
	WorkMode *AgentWorkMode              `json:"workMode,omitempty"`
	Codex    *CodexExecutionConfigInput  `json:"codex,omitempty"`
	Claude   *ClaudeExecutionConfigInput `json:"claude,omitempty"`
}

type AgentRuntimeEnvVar struct {
	Key         string  `json:"key"`
	ValueMasked string  `json:"valueMasked"`
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Sensitive   bool    `json:"sensitive"`
}

type AgentRuntimeEnvVarInput struct {
	Key         string  `json:"key"`
	Value       *string `json:"value,omitempty"`
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Sensitive   bool    `json:"sensitive"`
}

type AssignWorkerInput struct {
	TaskID      string                     `json:"taskId"`
	WorkerID    string                     `json:"workerId"`
	AgentType   *AgentType                 `json:"agentType,omitempty"`
	AgentConfig *AgentExecutionConfigInput `json:"agentConfig,omitempty"`
}

type Board struct {
	ID            string               `json:"id"`
	Name          string               `json:"name"`
	Type          BoardType            `json:"type"`
	Columns       []*BoardColumn       `json:"columns"`
	CalendarItems []*BoardCalendarItem `json:"calendarItems"`
	Tasks         []*Task              `json:"tasks"`
}

type BoardCalendarItem struct {
	ID     string     `json:"id"`
	Task   *Task      `json:"task"`
	Date   time.Time  `json:"date"`
	Status TaskStatus `json:"status"`
}

type BoardColumn struct {
	ID     string     `json:"id"`
	Title  string     `json:"title"`
	Status TaskStatus `json:"status"`
	Tasks  []*Task    `json:"tasks"`
}

type ClaudeExecutionConfig struct {
	Model          *string               `json:"model,omitempty"`
	Effort         *ClaudeEffort         `json:"effort,omitempty"`
	PermissionMode *ClaudePermissionMode `json:"permissionMode,omitempty"`
}

type ClaudeExecutionConfigInput struct {
	Model          *string               `json:"model,omitempty"`
	Effort         *ClaudeEffort         `json:"effort,omitempty"`
	PermissionMode *ClaudePermissionMode `json:"permissionMode,omitempty"`
}

type CodexExecutionConfig struct {
	Model                     *string               `json:"model,omitempty"`
	ReasoningEffort           *CodexReasoningEffort `json:"reasoningEffort,omitempty"`
	SandboxMode               *CodexSandboxMode     `json:"sandboxMode,omitempty"`
	ApprovalPolicy            *CodexApprovalPolicy  `json:"approvalPolicy,omitempty"`
	FullAuto                  bool                  `json:"fullAuto"`
	BypassApprovalsAndSandbox bool                  `json:"bypassApprovalsAndSandbox"`
}

type CodexExecutionConfigInput struct {
	Model                     *string               `json:"model,omitempty"`
	ReasoningEffort           *CodexReasoningEffort `json:"reasoningEffort,omitempty"`
	SandboxMode               *CodexSandboxMode     `json:"sandboxMode,omitempty"`
	ApprovalPolicy            *CodexApprovalPolicy  `json:"approvalPolicy,omitempty"`
	FullAuto                  *bool                 `json:"fullAuto,omitempty"`
	BypassApprovalsAndSandbox *bool                 `json:"bypassApprovalsAndSandbox,omitempty"`
}

type ContinueTaskInput struct {
	TaskID  string `json:"taskId"`
	Message string `json:"message"`
}

type ConversationMessage struct {
	ID        string      `json:"id"`
	TaskID    string      `json:"taskId"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	Metadata  []*KeyValue `json:"metadata"`
	CreatedAt time.Time   `json:"createdAt"`
}

type CreateProjectInput struct {
	Name               string  `json:"name"`
	GitURL             string  `json:"gitUrl"`
	DefaultBranch      *string `json:"defaultBranch,omitempty"`
	WorktreeNamePrefix *string `json:"worktreeNamePrefix,omitempty"`
}

type CreateTaskInput struct {
	Title        string                     `json:"title"`
	Description  *string                    `json:"description,omitempty"`
	ProjectID    string                     `json:"projectId"`
	WorkerID     *string                    `json:"workerId,omitempty"`
	AgentType    *AgentType                 `json:"agentType,omitempty"`
	AgentConfig  *AgentExecutionConfigInput `json:"agentConfig,omitempty"`
	BaseBranch   *string                    `json:"baseBranch,omitempty"`
	PreCommands  []string                   `json:"preCommands,omitempty"`
	PostCommands []string                   `json:"postCommands,omitempty"`
	StartDate    *time.Time                 `json:"startDate,omitempty"`
	EndDate      *time.Time                 `json:"endDate,omitempty"`
}

type CreateWorkerInput struct {
	ID                 *string                       `json:"id,omitempty"`
	Name               string                        `json:"name"`
	SupportedAgents    []AgentType                   `json:"supportedAgents"`
	WorkDir            string                        `json:"workDir"`
	StartupCommand     *string                       `json:"startupCommand,omitempty"`
	ProjectBindingMode *WorkerProjectBindingMode     `json:"projectBindingMode,omitempty"`
	BoundProjectIds    []string                      `json:"boundProjectIds,omitempty"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnvInput `json:"agentRuntimeEnv,omitempty"`
	Capabilities       []*KeyValueInput              `json:"capabilities,omitempty"`
}

type DomainEvent struct {
	EventID          string    `json:"eventId"`
	EventType        string    `json:"eventType"`
	AggregateType    string    `json:"aggregateType"`
	AggregateID      string    `json:"aggregateId"`
	AggregateVersion int       `json:"aggregateVersion"`
	Payload          string    `json:"payload"`
	OccurredAt       time.Time `json:"occurredAt"`
	CorrelationID    *string   `json:"correlationId,omitempty"`
	CausationID      *string   `json:"causationId,omitempty"`
}

type DomainEventFilter struct {
	AggregateID   *string `json:"aggregateId,omitempty"`
	AggregateType *string `json:"aggregateType,omitempty"`
	EventType     *string `json:"eventType,omitempty"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type OutboxMessage struct {
	ID          string       `json:"id"`
	Event       *DomainEvent `json:"event"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"createdAt"`
	PublishedAt *time.Time   `json:"publishedAt,omitempty"`
}

type PageInput struct {
	Offset *int `json:"offset,omitempty"`
	Limit  *int `json:"limit,omitempty"`
}

type Project struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	GitURL             string    `json:"gitUrl"`
	DefaultBranch      string    `json:"defaultBranch"`
	WorktreeNamePrefix string    `json:"worktreeNamePrefix"`
	Archived           bool      `json:"archived"`
	Version            int       `json:"version"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type ProjectFilter struct {
	IncludeArchived *bool `json:"includeArchived,omitempty"`
}

type Query struct {
}

type RegisterWorkerInput struct {
	ID                 *string                       `json:"id,omitempty"`
	Name               string                        `json:"name"`
	SupportedAgents    []AgentType                   `json:"supportedAgents"`
	WorkDir            string                        `json:"workDir"`
	StartupCommand     *string                       `json:"startupCommand,omitempty"`
	ProjectBindingMode *WorkerProjectBindingMode     `json:"projectBindingMode,omitempty"`
	BoundProjectIds    []string                      `json:"boundProjectIds,omitempty"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnvInput `json:"agentRuntimeEnv,omitempty"`
	Capabilities       []*KeyValueInput              `json:"capabilities,omitempty"`
}

type Settings struct {
	ID                     string    `json:"id"`
	Version                int       `json:"version"`
	WorkerHeartbeatTimeout string    `json:"workerHeartbeatTimeout"`
	SecurityPolicy         string    `json:"securityPolicy"`
	CreatedAt              time.Time `json:"createdAt"`
	UpdatedAt              time.Time `json:"updatedAt"`
}

type StartTaskInput struct {
	TaskID string `json:"taskId"`
}

type Subscription struct {
}

type Task struct {
	ID             string                `json:"id"`
	Title          string                `json:"title"`
	Description    string                `json:"description"`
	Status         TaskStatus            `json:"status"`
	ProjectID      string                `json:"projectId"`
	WorkerID       *string               `json:"workerId,omitempty"`
	AgentType      *AgentType            `json:"agentType,omitempty"`
	AgentConfig    *AgentExecutionConfig `json:"agentConfig"`
	BaseBranch     string                `json:"baseBranch"`
	WorktreePath   *string               `json:"worktreePath,omitempty"`
	AgentSessionID *string               `json:"agentSessionId,omitempty"`
	PreCommands    []string              `json:"preCommands"`
	PostCommands   []string              `json:"postCommands"`
	Result         *string               `json:"result,omitempty"`
	StartDate      time.Time             `json:"startDate"`
	EndDate        time.Time             `json:"endDate"`
	Version        int                   `json:"version"`
	CreatedAt      time.Time             `json:"createdAt"`
	UpdatedAt      time.Time             `json:"updatedAt"`
}

type TaskConnection struct {
	Nodes      []*Task `json:"nodes"`
	TotalCount int     `json:"totalCount"`
}

type TaskFilter struct {
	Status          *TaskStatus `json:"status,omitempty"`
	ProjectID       *string     `json:"projectId,omitempty"`
	WorkerID        *string     `json:"workerId,omitempty"`
	AgentType       *AgentType  `json:"agentType,omitempty"`
	IncludeArchived *bool       `json:"includeArchived,omitempty"`
}

type TaskLog struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"taskId"`
	Stream    string    `json:"stream"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type UpdateProjectInput struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	GitURL             string `json:"gitUrl"`
	DefaultBranch      string `json:"defaultBranch"`
	WorktreeNamePrefix string `json:"worktreeNamePrefix"`
}

type UpdateTaskInput struct {
	ID           string     `json:"id"`
	Title        string     `json:"title"`
	Description  *string    `json:"description,omitempty"`
	ProjectID    string     `json:"projectId"`
	AgentType    *AgentType `json:"agentType,omitempty"`
	BaseBranch   *string    `json:"baseBranch,omitempty"`
	PreCommands  []string   `json:"preCommands,omitempty"`
	PostCommands []string   `json:"postCommands,omitempty"`
	StartDate    *time.Time `json:"startDate,omitempty"`
	EndDate      *time.Time `json:"endDate,omitempty"`
}

type UpdateWorkerInput struct {
	ID                 string                        `json:"id"`
	Name               string                        `json:"name"`
	SupportedAgents    []AgentType                   `json:"supportedAgents"`
	WorkDir            string                        `json:"workDir"`
	StartupCommand     *string                       `json:"startupCommand,omitempty"`
	ProjectBindingMode WorkerProjectBindingMode      `json:"projectBindingMode"`
	BoundProjectIds    []string                      `json:"boundProjectIds,omitempty"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnvInput `json:"agentRuntimeEnv,omitempty"`
	Capabilities       []*KeyValueInput              `json:"capabilities,omitempty"`
}

type UpdateWorkerProjectBindingsInput struct {
	WorkerID           string                   `json:"workerId"`
	ProjectBindingMode WorkerProjectBindingMode `json:"projectBindingMode"`
	BoundProjectIds    []string                 `json:"boundProjectIds,omitempty"`
}

type Worker struct {
	ID                 string                   `json:"id"`
	Name               string                   `json:"name"`
	Status             WorkerStatus             `json:"status"`
	Capabilities       []*KeyValue              `json:"capabilities"`
	SupportedAgents    []AgentType              `json:"supportedAgents"`
	WorkDir            string                   `json:"workDir"`
	StartupCommand     *string                  `json:"startupCommand,omitempty"`
	ProjectBindingMode WorkerProjectBindingMode `json:"projectBindingMode"`
	BoundProjectIds    []string                 `json:"boundProjectIds"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnv `json:"agentRuntimeEnv"`
	CurrentTaskID      *string                  `json:"currentTaskId,omitempty"`
	LastHeartbeatAt    *time.Time               `json:"lastHeartbeatAt,omitempty"`
	Version            int                      `json:"version"`
	CreatedAt          time.Time                `json:"createdAt"`
	UpdatedAt          time.Time                `json:"updatedAt"`
}

type WorkerAgentRuntimeEnv struct {
	AgentType AgentType             `json:"agentType"`
	Vars      []*AgentRuntimeEnvVar `json:"vars"`
}

type WorkerAgentRuntimeEnvInput struct {
	AgentType AgentType                  `json:"agentType"`
	Vars      []*AgentRuntimeEnvVarInput `json:"vars"`
}

type WorkerFilter struct {
	Status          *WorkerStatus `json:"status,omitempty"`
	ProjectID       *string       `json:"projectId,omitempty"`
	AgentType       *AgentType    `json:"agentType,omitempty"`
	IncludeDisabled *bool         `json:"includeDisabled,omitempty"`
}

type AgentType string

const (
	AgentTypeCodex  AgentType = "codex"
	AgentTypeClaude AgentType = "claude"
)

var AllAgentType = []AgentType{
	AgentTypeCodex,
	AgentTypeClaude,
}

func (e AgentType) IsValid() bool {
	switch e {
	case AgentTypeCodex, AgentTypeClaude:
		return true
	}
	return false
}

func (e AgentType) String() string {
	return string(e)
}

func (e *AgentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentType", str)
	}
	return nil
}

func (e AgentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentWorkMode string

const (
	AgentWorkModePlan      AgentWorkMode = "PLAN"
	AgentWorkModeImplement AgentWorkMode = "IMPLEMENT"
	AgentWorkModeReview    AgentWorkMode = "REVIEW"
)

var AllAgentWorkMode = []AgentWorkMode{
	AgentWorkModePlan,
	AgentWorkModeImplement,
	AgentWorkModeReview,
}

func (e AgentWorkMode) IsValid() bool {
	switch e {
	case AgentWorkModePlan, AgentWorkModeImplement, AgentWorkModeReview:
		return true
	}
	return false
}

func (e AgentWorkMode) String() string {
	return string(e)
}

func (e *AgentWorkMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentWorkMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentWorkMode", str)
	}
	return nil
}

func (e AgentWorkMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentWorkMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentWorkMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BoardType string

const (
	BoardTypeKanban   BoardType = "KANBAN"
	BoardTypeCalendar BoardType = "CALENDAR"
	BoardTypeList     BoardType = "LIST"
)

var AllBoardType = []BoardType{
	BoardTypeKanban,
	BoardTypeCalendar,
	BoardTypeList,
}

func (e BoardType) IsValid() bool {
	switch e {
	case BoardTypeKanban, BoardTypeCalendar, BoardTypeList:
		return true
	}
	return false
}

func (e BoardType) String() string {
	return string(e)
}

func (e *BoardType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BoardType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BoardType", str)
	}
	return nil
}

func (e BoardType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BoardType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BoardType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ClaudeEffort string

const (
	ClaudeEffortLow    ClaudeEffort = "LOW"
	ClaudeEffortMedium ClaudeEffort = "MEDIUM"
	ClaudeEffortHigh   ClaudeEffort = "HIGH"
	ClaudeEffortXhigh  ClaudeEffort = "XHIGH"
	ClaudeEffortMax    ClaudeEffort = "MAX"
)

var AllClaudeEffort = []ClaudeEffort{
	ClaudeEffortLow,
	ClaudeEffortMedium,
	ClaudeEffortHigh,
	ClaudeEffortXhigh,
	ClaudeEffortMax,
}

func (e ClaudeEffort) IsValid() bool {
	switch e {
	case ClaudeEffortLow, ClaudeEffortMedium, ClaudeEffortHigh, ClaudeEffortXhigh, ClaudeEffortMax:
		return true
	}
	return false
}

func (e ClaudeEffort) String() string {
	return string(e)
}

func (e *ClaudeEffort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClaudeEffort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClaudeEffort", str)
	}
	return nil
}

func (e ClaudeEffort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClaudeEffort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClaudeEffort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ClaudePermissionMode string

const (
	ClaudePermissionModeAcceptEdits       ClaudePermissionMode = "ACCEPT_EDITS"
	ClaudePermissionModeAuto              ClaudePermissionMode = "AUTO"
	ClaudePermissionModeBypassPermissions ClaudePermissionMode = "BYPASS_PERMISSIONS"
	ClaudePermissionModeDefault           ClaudePermissionMode = "DEFAULT"
	ClaudePermissionModeDontAsk           ClaudePermissionMode = "DONT_ASK"
	ClaudePermissionModePlan              ClaudePermissionMode = "PLAN"
)

var AllClaudePermissionMode = []ClaudePermissionMode{
	ClaudePermissionModeAcceptEdits,
	ClaudePermissionModeAuto,
	ClaudePermissionModeBypassPermissions,
	ClaudePermissionModeDefault,
	ClaudePermissionModeDontAsk,
	ClaudePermissionModePlan,
}

func (e ClaudePermissionMode) IsValid() bool {
	switch e {
	case ClaudePermissionModeAcceptEdits, ClaudePermissionModeAuto, ClaudePermissionModeBypassPermissions, ClaudePermissionModeDefault, ClaudePermissionModeDontAsk, ClaudePermissionModePlan:
		return true
	}
	return false
}

func (e ClaudePermissionMode) String() string {
	return string(e)
}

func (e *ClaudePermissionMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClaudePermissionMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClaudePermissionMode", str)
	}
	return nil
}

func (e ClaudePermissionMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClaudePermissionMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClaudePermissionMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CodexApprovalPolicy string

const (
	CodexApprovalPolicyUntrusted CodexApprovalPolicy = "UNTRUSTED"
	CodexApprovalPolicyOnFailure CodexApprovalPolicy = "ON_FAILURE"
	CodexApprovalPolicyOnRequest CodexApprovalPolicy = "ON_REQUEST"
	CodexApprovalPolicyNever     CodexApprovalPolicy = "NEVER"
)

var AllCodexApprovalPolicy = []CodexApprovalPolicy{
	CodexApprovalPolicyUntrusted,
	CodexApprovalPolicyOnFailure,
	CodexApprovalPolicyOnRequest,
	CodexApprovalPolicyNever,
}

func (e CodexApprovalPolicy) IsValid() bool {
	switch e {
	case CodexApprovalPolicyUntrusted, CodexApprovalPolicyOnFailure, CodexApprovalPolicyOnRequest, CodexApprovalPolicyNever:
		return true
	}
	return false
}

func (e CodexApprovalPolicy) String() string {
	return string(e)
}

func (e *CodexApprovalPolicy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CodexApprovalPolicy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CodexApprovalPolicy", str)
	}
	return nil
}

func (e CodexApprovalPolicy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CodexApprovalPolicy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CodexApprovalPolicy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CodexReasoningEffort string

const (
	CodexReasoningEffortMinimal CodexReasoningEffort = "MINIMAL"
	CodexReasoningEffortLow     CodexReasoningEffort = "LOW"
	CodexReasoningEffortMedium  CodexReasoningEffort = "MEDIUM"
	CodexReasoningEffortHigh    CodexReasoningEffort = "HIGH"
	CodexReasoningEffortXhigh   CodexReasoningEffort = "XHIGH"
)

var AllCodexReasoningEffort = []CodexReasoningEffort{
	CodexReasoningEffortMinimal,
	CodexReasoningEffortLow,
	CodexReasoningEffortMedium,
	CodexReasoningEffortHigh,
	CodexReasoningEffortXhigh,
}

func (e CodexReasoningEffort) IsValid() bool {
	switch e {
	case CodexReasoningEffortMinimal, CodexReasoningEffortLow, CodexReasoningEffortMedium, CodexReasoningEffortHigh, CodexReasoningEffortXhigh:
		return true
	}
	return false
}

func (e CodexReasoningEffort) String() string {
	return string(e)
}

func (e *CodexReasoningEffort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CodexReasoningEffort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CodexReasoningEffort", str)
	}
	return nil
}

func (e CodexReasoningEffort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CodexReasoningEffort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CodexReasoningEffort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CodexSandboxMode string

const (
	CodexSandboxModeReadOnly         CodexSandboxMode = "READ_ONLY"
	CodexSandboxModeWorkspaceWrite   CodexSandboxMode = "WORKSPACE_WRITE"
	CodexSandboxModeDangerFullAccess CodexSandboxMode = "DANGER_FULL_ACCESS"
)

var AllCodexSandboxMode = []CodexSandboxMode{
	CodexSandboxModeReadOnly,
	CodexSandboxModeWorkspaceWrite,
	CodexSandboxModeDangerFullAccess,
}

func (e CodexSandboxMode) IsValid() bool {
	switch e {
	case CodexSandboxModeReadOnly, CodexSandboxModeWorkspaceWrite, CodexSandboxModeDangerFullAccess:
		return true
	}
	return false
}

func (e CodexSandboxMode) String() string {
	return string(e)
}

func (e *CodexSandboxMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CodexSandboxMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CodexSandboxMode", str)
	}
	return nil
}

func (e CodexSandboxMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CodexSandboxMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CodexSandboxMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusCreated      TaskStatus = "CREATED"
	TaskStatusAssigned     TaskStatus = "ASSIGNED"
	TaskStatusStarting     TaskStatus = "STARTING"
	TaskStatusRunning      TaskStatus = "RUNNING"
	TaskStatusWaitingInput TaskStatus = "WAITING_INPUT"
	TaskStatusInterrupting TaskStatus = "INTERRUPTING"
	TaskStatusInterrupted  TaskStatus = "INTERRUPTED"
	TaskStatusCompleted    TaskStatus = "COMPLETED"
	TaskStatusFailed       TaskStatus = "FAILED"
	TaskStatusArchived     TaskStatus = "ARCHIVED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusCreated,
	TaskStatusAssigned,
	TaskStatusStarting,
	TaskStatusRunning,
	TaskStatusWaitingInput,
	TaskStatusInterrupting,
	TaskStatusInterrupted,
	TaskStatusCompleted,
	TaskStatusFailed,
	TaskStatusArchived,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusCreated, TaskStatusAssigned, TaskStatusStarting, TaskStatusRunning, TaskStatusWaitingInput, TaskStatusInterrupting, TaskStatusInterrupted, TaskStatusCompleted, TaskStatusFailed, TaskStatusArchived:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerProjectBindingMode string

const (
	WorkerProjectBindingModeAllProjects      WorkerProjectBindingMode = "ALL_PROJECTS"
	WorkerProjectBindingModeSpecificProjects WorkerProjectBindingMode = "SPECIFIC_PROJECTS"
)

var AllWorkerProjectBindingMode = []WorkerProjectBindingMode{
	WorkerProjectBindingModeAllProjects,
	WorkerProjectBindingModeSpecificProjects,
}

func (e WorkerProjectBindingMode) IsValid() bool {
	switch e {
	case WorkerProjectBindingModeAllProjects, WorkerProjectBindingModeSpecificProjects:
		return true
	}
	return false
}

func (e WorkerProjectBindingMode) String() string {
	return string(e)
}

func (e *WorkerProjectBindingMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerProjectBindingMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerProjectBindingMode", str)
	}
	return nil
}

func (e WorkerProjectBindingMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerProjectBindingMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerProjectBindingMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerStatus string

const (
	WorkerStatusRegistered WorkerStatus = "REGISTERED"
	WorkerStatusOnline     WorkerStatus = "ONLINE"
	WorkerStatusOffline    WorkerStatus = "OFFLINE"
	WorkerStatusError      WorkerStatus = "ERROR"
	WorkerStatusDisabled   WorkerStatus = "DISABLED"
)

var AllWorkerStatus = []WorkerStatus{
	WorkerStatusRegistered,
	WorkerStatusOnline,
	WorkerStatusOffline,
	WorkerStatusError,
	WorkerStatusDisabled,
}

func (e WorkerStatus) IsValid() bool {
	switch e {
	case WorkerStatusRegistered, WorkerStatusOnline, WorkerStatusOffline, WorkerStatusError, WorkerStatusDisabled:
		return true
	}
	return false
}

func (e WorkerStatus) String() string {
	return string(e)
}

func (e *WorkerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerStatus", str)
	}
	return nil
}

func (e WorkerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
