// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AgentRuntimeEnvVar struct {
	Key         string  `json:"key"`
	ValueMasked string  `json:"valueMasked"`
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Sensitive   bool    `json:"sensitive"`
}

type AgentRuntimeEnvVarInput struct {
	Key         string  `json:"key"`
	Value       *string `json:"value,omitempty"`
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Sensitive   bool    `json:"sensitive"`
}

type AssignWorkerInput struct {
	TaskID    string     `json:"taskId"`
	WorkerID  string     `json:"workerId"`
	AgentType *AgentType `json:"agentType,omitempty"`
}

type Board struct {
	ID            string               `json:"id"`
	Name          string               `json:"name"`
	Type          BoardType            `json:"type"`
	Columns       []*BoardColumn       `json:"columns"`
	CalendarItems []*BoardCalendarItem `json:"calendarItems"`
	Tasks         []*Task              `json:"tasks"`
}

type BoardCalendarItem struct {
	ID     string     `json:"id"`
	Task   *Task      `json:"task"`
	Date   time.Time  `json:"date"`
	Status TaskStatus `json:"status"`
}

type BoardColumn struct {
	ID     string     `json:"id"`
	Title  string     `json:"title"`
	Status TaskStatus `json:"status"`
	Tasks  []*Task    `json:"tasks"`
}

type ConversationMessage struct {
	ID        string      `json:"id"`
	TaskID    string      `json:"taskId"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	Metadata  []*KeyValue `json:"metadata"`
	CreatedAt time.Time   `json:"createdAt"`
}

type CreateProjectInput struct {
	Name               string  `json:"name"`
	GitURL             string  `json:"gitUrl"`
	DefaultBranch      *string `json:"defaultBranch,omitempty"`
	WorktreeNamePrefix *string `json:"worktreeNamePrefix,omitempty"`
}

type CreateTaskInput struct {
	Title        string     `json:"title"`
	Description  *string    `json:"description,omitempty"`
	ProjectID    string     `json:"projectId"`
	WorkerID     *string    `json:"workerId,omitempty"`
	AgentType    *AgentType `json:"agentType,omitempty"`
	BaseBranch   *string    `json:"baseBranch,omitempty"`
	PreCommands  []string   `json:"preCommands,omitempty"`
	PostCommands []string   `json:"postCommands,omitempty"`
}

type CreateWorkerInput struct {
	ID                 *string                   `json:"id,omitempty"`
	Name               string                    `json:"name"`
	SupportedAgents    []AgentType               `json:"supportedAgents"`
	WorkDir            string                    `json:"workDir"`
	StartupCommand     *string                   `json:"startupCommand,omitempty"`
	ProjectBindingMode *WorkerProjectBindingMode `json:"projectBindingMode,omitempty"`
	BoundProjectIds    []string                  `json:"boundProjectIds,omitempty"`
	Capabilities       []*KeyValueInput          `json:"capabilities,omitempty"`
}

type DomainEvent struct {
	EventID          string    `json:"eventId"`
	EventType        string    `json:"eventType"`
	AggregateType    string    `json:"aggregateType"`
	AggregateID      string    `json:"aggregateId"`
	AggregateVersion int       `json:"aggregateVersion"`
	Payload          string    `json:"payload"`
	OccurredAt       time.Time `json:"occurredAt"`
	CorrelationID    *string   `json:"correlationId,omitempty"`
	CausationID      *string   `json:"causationId,omitempty"`
}

type DomainEventFilter struct {
	AggregateID   *string `json:"aggregateId,omitempty"`
	AggregateType *string `json:"aggregateType,omitempty"`
	EventType     *string `json:"eventType,omitempty"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type OutboxMessage struct {
	ID          string       `json:"id"`
	Event       *DomainEvent `json:"event"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"createdAt"`
	PublishedAt *time.Time   `json:"publishedAt,omitempty"`
}

type PageInput struct {
	Offset *int `json:"offset,omitempty"`
	Limit  *int `json:"limit,omitempty"`
}

type Project struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	GitURL             string    `json:"gitUrl"`
	DefaultBranch      string    `json:"defaultBranch"`
	WorktreeNamePrefix string    `json:"worktreeNamePrefix"`
	Archived           bool      `json:"archived"`
	Version            int       `json:"version"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type ProjectFilter struct {
	IncludeArchived *bool `json:"includeArchived,omitempty"`
}

type Query struct {
}

type RegisterWorkerInput struct {
	ID                 *string                   `json:"id,omitempty"`
	Name               string                    `json:"name"`
	SupportedAgents    []AgentType               `json:"supportedAgents"`
	WorkDir            string                    `json:"workDir"`
	StartupCommand     *string                   `json:"startupCommand,omitempty"`
	ProjectBindingMode *WorkerProjectBindingMode `json:"projectBindingMode,omitempty"`
	BoundProjectIds    []string                  `json:"boundProjectIds,omitempty"`
	Capabilities       []*KeyValueInput          `json:"capabilities,omitempty"`
}

type Settings struct {
	ID                     string                `json:"id"`
	Version                int                   `json:"version"`
	AgentRuntimeEnvVars    []*AgentRuntimeEnvVar `json:"agentRuntimeEnvVars"`
	WorkerHeartbeatTimeout string                `json:"workerHeartbeatTimeout"`
	SecurityPolicy         string                `json:"securityPolicy"`
	CreatedAt              time.Time             `json:"createdAt"`
	UpdatedAt              time.Time             `json:"updatedAt"`
}

type StartTaskInput struct {
	TaskID string `json:"taskId"`
}

type Subscription struct {
}

type Task struct {
	ID           string     `json:"id"`
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	Status       TaskStatus `json:"status"`
	ProjectID    string     `json:"projectId"`
	WorkerID     *string    `json:"workerId,omitempty"`
	AgentType    *AgentType `json:"agentType,omitempty"`
	BaseBranch   string     `json:"baseBranch"`
	WorktreePath *string    `json:"worktreePath,omitempty"`
	PreCommands  []string   `json:"preCommands"`
	PostCommands []string   `json:"postCommands"`
	Result       *string    `json:"result,omitempty"`
	Version      int        `json:"version"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
}

type TaskConnection struct {
	Nodes      []*Task `json:"nodes"`
	TotalCount int     `json:"totalCount"`
}

type TaskFilter struct {
	Status          *TaskStatus `json:"status,omitempty"`
	ProjectID       *string     `json:"projectId,omitempty"`
	WorkerID        *string     `json:"workerId,omitempty"`
	AgentType       *AgentType  `json:"agentType,omitempty"`
	IncludeArchived *bool       `json:"includeArchived,omitempty"`
}

type TaskLog struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"taskId"`
	Stream    string    `json:"stream"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type UpdateAgentRuntimeEnvVarsInput struct {
	Vars []*AgentRuntimeEnvVarInput `json:"vars"`
}

type UpdateProjectInput struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	GitURL             string `json:"gitUrl"`
	DefaultBranch      string `json:"defaultBranch"`
	WorktreeNamePrefix string `json:"worktreeNamePrefix"`
}

type UpdateTaskInput struct {
	ID           string     `json:"id"`
	Title        string     `json:"title"`
	Description  *string    `json:"description,omitempty"`
	ProjectID    string     `json:"projectId"`
	AgentType    *AgentType `json:"agentType,omitempty"`
	BaseBranch   *string    `json:"baseBranch,omitempty"`
	PreCommands  []string   `json:"preCommands,omitempty"`
	PostCommands []string   `json:"postCommands,omitempty"`
}

type UpdateWorkerInput struct {
	ID                 string                   `json:"id"`
	Name               string                   `json:"name"`
	SupportedAgents    []AgentType              `json:"supportedAgents"`
	WorkDir            string                   `json:"workDir"`
	StartupCommand     *string                  `json:"startupCommand,omitempty"`
	ProjectBindingMode WorkerProjectBindingMode `json:"projectBindingMode"`
	BoundProjectIds    []string                 `json:"boundProjectIds,omitempty"`
	Capabilities       []*KeyValueInput         `json:"capabilities,omitempty"`
}

type UpdateWorkerProjectBindingsInput struct {
	WorkerID           string                   `json:"workerId"`
	ProjectBindingMode WorkerProjectBindingMode `json:"projectBindingMode"`
	BoundProjectIds    []string                 `json:"boundProjectIds,omitempty"`
}

type Worker struct {
	ID                 string                   `json:"id"`
	Name               string                   `json:"name"`
	Status             WorkerStatus             `json:"status"`
	Capabilities       []*KeyValue              `json:"capabilities"`
	SupportedAgents    []AgentType              `json:"supportedAgents"`
	WorkDir            string                   `json:"workDir"`
	StartupCommand     *string                  `json:"startupCommand,omitempty"`
	ProjectBindingMode WorkerProjectBindingMode `json:"projectBindingMode"`
	BoundProjectIds    []string                 `json:"boundProjectIds"`
	CurrentTaskID      *string                  `json:"currentTaskId,omitempty"`
	LastHeartbeatAt    *time.Time               `json:"lastHeartbeatAt,omitempty"`
	Version            int                      `json:"version"`
	CreatedAt          time.Time                `json:"createdAt"`
	UpdatedAt          time.Time                `json:"updatedAt"`
}

type WorkerFilter struct {
	Status          *WorkerStatus `json:"status,omitempty"`
	ProjectID       *string       `json:"projectId,omitempty"`
	AgentType       *AgentType    `json:"agentType,omitempty"`
	IncludeDisabled *bool         `json:"includeDisabled,omitempty"`
}

type AgentType string

const (
	AgentTypeCodex  AgentType = "codex"
	AgentTypeClaude AgentType = "claude"
)

var AllAgentType = []AgentType{
	AgentTypeCodex,
	AgentTypeClaude,
}

func (e AgentType) IsValid() bool {
	switch e {
	case AgentTypeCodex, AgentTypeClaude:
		return true
	}
	return false
}

func (e AgentType) String() string {
	return string(e)
}

func (e *AgentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentType", str)
	}
	return nil
}

func (e AgentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BoardType string

const (
	BoardTypeKanban   BoardType = "KANBAN"
	BoardTypeCalendar BoardType = "CALENDAR"
	BoardTypeList     BoardType = "LIST"
)

var AllBoardType = []BoardType{
	BoardTypeKanban,
	BoardTypeCalendar,
	BoardTypeList,
}

func (e BoardType) IsValid() bool {
	switch e {
	case BoardTypeKanban, BoardTypeCalendar, BoardTypeList:
		return true
	}
	return false
}

func (e BoardType) String() string {
	return string(e)
}

func (e *BoardType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BoardType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BoardType", str)
	}
	return nil
}

func (e BoardType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BoardType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BoardType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusCreated      TaskStatus = "CREATED"
	TaskStatusAssigned     TaskStatus = "ASSIGNED"
	TaskStatusStarting     TaskStatus = "STARTING"
	TaskStatusRunning      TaskStatus = "RUNNING"
	TaskStatusWaitingInput TaskStatus = "WAITING_INPUT"
	TaskStatusInterrupting TaskStatus = "INTERRUPTING"
	TaskStatusInterrupted  TaskStatus = "INTERRUPTED"
	TaskStatusCompleted    TaskStatus = "COMPLETED"
	TaskStatusFailed       TaskStatus = "FAILED"
	TaskStatusArchived     TaskStatus = "ARCHIVED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusCreated,
	TaskStatusAssigned,
	TaskStatusStarting,
	TaskStatusRunning,
	TaskStatusWaitingInput,
	TaskStatusInterrupting,
	TaskStatusInterrupted,
	TaskStatusCompleted,
	TaskStatusFailed,
	TaskStatusArchived,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusCreated, TaskStatusAssigned, TaskStatusStarting, TaskStatusRunning, TaskStatusWaitingInput, TaskStatusInterrupting, TaskStatusInterrupted, TaskStatusCompleted, TaskStatusFailed, TaskStatusArchived:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerProjectBindingMode string

const (
	WorkerProjectBindingModeAllProjects      WorkerProjectBindingMode = "ALL_PROJECTS"
	WorkerProjectBindingModeSpecificProjects WorkerProjectBindingMode = "SPECIFIC_PROJECTS"
)

var AllWorkerProjectBindingMode = []WorkerProjectBindingMode{
	WorkerProjectBindingModeAllProjects,
	WorkerProjectBindingModeSpecificProjects,
}

func (e WorkerProjectBindingMode) IsValid() bool {
	switch e {
	case WorkerProjectBindingModeAllProjects, WorkerProjectBindingModeSpecificProjects:
		return true
	}
	return false
}

func (e WorkerProjectBindingMode) String() string {
	return string(e)
}

func (e *WorkerProjectBindingMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerProjectBindingMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerProjectBindingMode", str)
	}
	return nil
}

func (e WorkerProjectBindingMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerProjectBindingMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerProjectBindingMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerStatus string

const (
	WorkerStatusRegistered WorkerStatus = "REGISTERED"
	WorkerStatusOnline     WorkerStatus = "ONLINE"
	WorkerStatusOffline    WorkerStatus = "OFFLINE"
	WorkerStatusError      WorkerStatus = "ERROR"
	WorkerStatusDisabled   WorkerStatus = "DISABLED"
)

var AllWorkerStatus = []WorkerStatus{
	WorkerStatusRegistered,
	WorkerStatusOnline,
	WorkerStatusOffline,
	WorkerStatusError,
	WorkerStatusDisabled,
}

func (e WorkerStatus) IsValid() bool {
	switch e {
	case WorkerStatusRegistered, WorkerStatusOnline, WorkerStatusOffline, WorkerStatusError, WorkerStatusDisabled:
		return true
	}
	return false
}

func (e WorkerStatus) String() string {
	return string(e)
}

func (e *WorkerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerStatus", str)
	}
	return nil
}

func (e WorkerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
