// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddTaskReviewCommentInput struct {
	TaskID string `json:"taskId"`
	Path   string `json:"path"`
	Line   int    `json:"line"`
	Body   string `json:"body"`
}

type AgentExecutionConfig struct {
	WorkMode *AgentWorkMode         `json:"workMode,omitempty"`
	Codex    *CodexExecutionConfig  `json:"codex,omitempty"`
	Claude   *ClaudeExecutionConfig `json:"claude,omitempty"`
}

type AgentExecutionConfigInput struct {
	WorkMode *AgentWorkMode              `json:"workMode,omitempty"`
	Codex    *CodexExecutionConfigInput  `json:"codex,omitempty"`
	Claude   *ClaudeExecutionConfigInput `json:"claude,omitempty"`
}

type AgentRuntimeEnvVar struct {
	Key         string  `json:"key"`
	ValueMasked string  `json:"valueMasked"`
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Sensitive   bool    `json:"sensitive"`
}

type AgentRuntimeEnvVarInput struct {
	Key         string  `json:"key"`
	Value       *string `json:"value,omitempty"`
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Sensitive   bool    `json:"sensitive"`
}

type AssignWorkerInput struct {
	TaskID      string                     `json:"taskId"`
	WorkerID    string                     `json:"workerId"`
	AgentType   *AgentType                 `json:"agentType,omitempty"`
	AgentConfig *AgentExecutionConfigInput `json:"agentConfig,omitempty"`
}

type Board struct {
	ID            string               `json:"id"`
	Name          string               `json:"name"`
	Type          BoardType            `json:"type"`
	TotalCount    int                  `json:"totalCount"`
	Columns       []*BoardColumn       `json:"columns"`
	CalendarItems []*BoardCalendarItem `json:"calendarItems"`
	Tasks         []*Task              `json:"tasks"`
}

type BoardCalendarItem struct {
	ID     string     `json:"id"`
	Task   *Task      `json:"task"`
	Date   time.Time  `json:"date"`
	Status TaskStatus `json:"status"`
}

type BoardColumn struct {
	ID     string     `json:"id"`
	Title  string     `json:"title"`
	Status TaskStatus `json:"status"`
	Tasks  []*Task    `json:"tasks"`
}

type ClaudeExecutionConfig struct {
	Model          *string               `json:"model,omitempty"`
	Effort         *ClaudeEffort         `json:"effort,omitempty"`
	PermissionMode *ClaudePermissionMode `json:"permissionMode,omitempty"`
}

type ClaudeExecutionConfigInput struct {
	Model          *string               `json:"model,omitempty"`
	Effort         *ClaudeEffort         `json:"effort,omitempty"`
	PermissionMode *ClaudePermissionMode `json:"permissionMode,omitempty"`
}

type CodexExecutionConfig struct {
	Model                     *string               `json:"model,omitempty"`
	ReasoningEffort           *CodexReasoningEffort `json:"reasoningEffort,omitempty"`
	SandboxMode               *CodexSandboxMode     `json:"sandboxMode,omitempty"`
	ApprovalPolicy            *CodexApprovalPolicy  `json:"approvalPolicy,omitempty"`
	FullAuto                  bool                  `json:"fullAuto"`
	BypassApprovalsAndSandbox bool                  `json:"bypassApprovalsAndSandbox"`
}

type CodexExecutionConfigInput struct {
	Model                     *string               `json:"model,omitempty"`
	ReasoningEffort           *CodexReasoningEffort `json:"reasoningEffort,omitempty"`
	SandboxMode               *CodexSandboxMode     `json:"sandboxMode,omitempty"`
	ApprovalPolicy            *CodexApprovalPolicy  `json:"approvalPolicy,omitempty"`
	FullAuto                  *bool                 `json:"fullAuto,omitempty"`
	BypassApprovalsAndSandbox *bool                 `json:"bypassApprovalsAndSandbox,omitempty"`
}

type ContinueTaskInput struct {
	TaskID  string `json:"taskId"`
	Message string `json:"message"`
}

type ContinueTaskWithReviewFeedbackInput struct {
	TaskID     string   `json:"taskId"`
	FindingIds []string `json:"findingIds,omitempty"`
	CommentIds []string `json:"commentIds,omitempty"`
	Message    *string  `json:"message,omitempty"`
}

type ConversationMessage struct {
	ID        string      `json:"id"`
	TaskID    string      `json:"taskId"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	Metadata  []*KeyValue `json:"metadata"`
	CreatedAt time.Time   `json:"createdAt"`
}

type CreateProjectInput struct {
	Name               string  `json:"name"`
	GitURL             string  `json:"gitUrl"`
	DefaultBranch      *string `json:"defaultBranch,omitempty"`
	WorktreeNamePrefix *string `json:"worktreeNamePrefix,omitempty"`
}

type CreateTaskInput struct {
	Title        string                     `json:"title"`
	Description  *string                    `json:"description,omitempty"`
	ProjectID    string                     `json:"projectId"`
	WorkerID     *string                    `json:"workerId,omitempty"`
	AgentType    *AgentType                 `json:"agentType,omitempty"`
	AgentConfig  *AgentExecutionConfigInput `json:"agentConfig,omitempty"`
	BaseBranch   *string                    `json:"baseBranch,omitempty"`
	PreCommands  []string                   `json:"preCommands,omitempty"`
	PostCommands []string                   `json:"postCommands,omitempty"`
	StartDate    *time.Time                 `json:"startDate,omitempty"`
	EndDate      *time.Time                 `json:"endDate,omitempty"`
}

type CreateWorkerInput struct {
	ID                 *string                       `json:"id,omitempty"`
	Name               string                        `json:"name"`
	SupportedAgents    []AgentType                   `json:"supportedAgents"`
	WorkDir            string                        `json:"workDir"`
	StartupCommand     *string                       `json:"startupCommand,omitempty"`
	ProjectBindingMode *WorkerProjectBindingMode     `json:"projectBindingMode,omitempty"`
	BoundProjectIds    []string                      `json:"boundProjectIds,omitempty"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnvInput `json:"agentRuntimeEnv,omitempty"`
	Capabilities       []*KeyValueInput              `json:"capabilities,omitempty"`
}

type DomainEvent struct {
	EventID          string    `json:"eventId"`
	EventType        string    `json:"eventType"`
	AggregateType    string    `json:"aggregateType"`
	AggregateID      string    `json:"aggregateId"`
	AggregateVersion int       `json:"aggregateVersion"`
	Payload          string    `json:"payload"`
	OccurredAt       time.Time `json:"occurredAt"`
	CorrelationID    *string   `json:"correlationId,omitempty"`
	CausationID      *string   `json:"causationId,omitempty"`
}

type DomainEventConnection struct {
	Nodes      []*DomainEvent `json:"nodes"`
	TotalCount int            `json:"totalCount"`
}

type DomainEventFilter struct {
	AggregateID   *string `json:"aggregateId,omitempty"`
	AggregateType *string `json:"aggregateType,omitempty"`
	EventType     *string `json:"eventType,omitempty"`
	Search        *string `json:"search,omitempty"`
}

type DomainEventSortInput struct {
	Field     *DomainEventSortField `json:"field,omitempty"`
	Direction *SortDirection        `json:"direction,omitempty"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type OutboxMessage struct {
	ID          string       `json:"id"`
	Event       *DomainEvent `json:"event"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"createdAt"`
	PublishedAt *time.Time   `json:"publishedAt,omitempty"`
}

type PageInput struct {
	Offset *int `json:"offset,omitempty"`
	Limit  *int `json:"limit,omitempty"`
}

type Project struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	GitURL             string    `json:"gitUrl"`
	DefaultBranch      string    `json:"defaultBranch"`
	WorktreeNamePrefix string    `json:"worktreeNamePrefix"`
	Archived           bool      `json:"archived"`
	Version            int       `json:"version"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type ProjectConnection struct {
	Nodes      []*Project `json:"nodes"`
	TotalCount int        `json:"totalCount"`
}

type ProjectFilter struct {
	IncludeArchived *bool   `json:"includeArchived,omitempty"`
	Search          *string `json:"search,omitempty"`
}

type ProjectSortInput struct {
	Field     *ProjectSortField `json:"field,omitempty"`
	Direction *SortDirection    `json:"direction,omitempty"`
}

type Query struct {
}

type RegisterWorkerInput struct {
	ID                 *string                       `json:"id,omitempty"`
	Name               string                        `json:"name"`
	SupportedAgents    []AgentType                   `json:"supportedAgents"`
	WorkDir            string                        `json:"workDir"`
	StartupCommand     *string                       `json:"startupCommand,omitempty"`
	ProjectBindingMode *WorkerProjectBindingMode     `json:"projectBindingMode,omitempty"`
	BoundProjectIds    []string                      `json:"boundProjectIds,omitempty"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnvInput `json:"agentRuntimeEnv,omitempty"`
	Capabilities       []*KeyValueInput              `json:"capabilities,omitempty"`
}

type RespondTaskInteractionInput struct {
	InteractionID string                   `json:"interactionId"`
	Decision      *TaskInteractionDecision `json:"decision,omitempty"`
	Message       *string                  `json:"message,omitempty"`
	Payload       *string                  `json:"payload,omitempty"`
}

type Settings struct {
	ID                     string    `json:"id"`
	Version                int       `json:"version"`
	WorkerHeartbeatTimeout string    `json:"workerHeartbeatTimeout"`
	SecurityPolicy         string    `json:"securityPolicy"`
	CreatedAt              time.Time `json:"createdAt"`
	UpdatedAt              time.Time `json:"updatedAt"`
}

type StartTaskInput struct {
	TaskID string `json:"taskId"`
}

type StartTaskReviewInput struct {
	TaskID string           `json:"taskId"`
	Scope  TaskGitDiffScope `json:"scope"`
}

type Subscription struct {
}

type Task struct {
	ID             string                `json:"id"`
	Title          string                `json:"title"`
	Description    string                `json:"description"`
	Status         TaskStatus            `json:"status"`
	ProjectID      string                `json:"projectId"`
	WorkerID       *string               `json:"workerId,omitempty"`
	AgentType      *AgentType            `json:"agentType,omitempty"`
	AgentConfig    *AgentExecutionConfig `json:"agentConfig"`
	BaseBranch     string                `json:"baseBranch"`
	WorktreePath   *string               `json:"worktreePath,omitempty"`
	AgentSessionID *string               `json:"agentSessionId,omitempty"`
	PreCommands    []string              `json:"preCommands"`
	PostCommands   []string              `json:"postCommands"`
	Result         *string               `json:"result,omitempty"`
	StartDate      time.Time             `json:"startDate"`
	EndDate        time.Time             `json:"endDate"`
	Version        int                   `json:"version"`
	CreatedAt      time.Time             `json:"createdAt"`
	UpdatedAt      time.Time             `json:"updatedAt"`
}

type TaskConnection struct {
	Nodes      []*Task `json:"nodes"`
	TotalCount int     `json:"totalCount"`
}

type TaskFilter struct {
	Status          *TaskStatus `json:"status,omitempty"`
	ProjectID       *string     `json:"projectId,omitempty"`
	WorkerID        *string     `json:"workerId,omitempty"`
	AgentType       *AgentType  `json:"agentType,omitempty"`
	IncludeArchived *bool       `json:"includeArchived,omitempty"`
	Search          *string     `json:"search,omitempty"`
}

type TaskGitBackup struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"taskId"`
	Paths     []string  `json:"paths"`
	PatchPath string    `json:"patchPath"`
	CreatedAt time.Time `json:"createdAt"`
}

type TaskGitChangeInput struct {
	TaskID   string   `json:"taskId"`
	Paths    []string `json:"paths,omitempty"`
	Patch    *string  `json:"patch,omitempty"`
	BackupID *string  `json:"backupId,omitempty"`
}

type TaskGitChangeResult struct {
	Ok     bool           `json:"ok"`
	Backup *TaskGitBackup `json:"backup,omitempty"`
	Diff   *TaskGitDiff   `json:"diff,omitempty"`
}

type TaskGitCommandInput struct {
	TaskID          string                  `json:"taskId"`
	Command         TaskGitCommand          `json:"command"`
	Message         *string                 `json:"message,omitempty"`
	Remote          *string                 `json:"remote,omitempty"`
	Branch          *string                 `json:"branch,omitempty"`
	PublishStrategy *TaskGitPublishStrategy `json:"publishStrategy,omitempty"`
}

type TaskGitCommandResult struct {
	Ok      bool           `json:"ok"`
	Command TaskGitCommand `json:"command"`
	Output  string         `json:"output"`
	HeadRef *string        `json:"headRef,omitempty"`
	BaseRef *string        `json:"baseRef,omitempty"`
	Diff    *TaskGitDiff   `json:"diff,omitempty"`
}

type TaskGitDiff struct {
	TaskID      string             `json:"taskId"`
	Scope       TaskGitDiffScope   `json:"scope"`
	BaseRef     *string            `json:"baseRef,omitempty"`
	HeadRef     *string            `json:"headRef,omitempty"`
	Files       []*TaskGitDiffFile `json:"files"`
	Truncated   bool               `json:"truncated"`
	GeneratedAt time.Time          `json:"generatedAt"`
}

type TaskGitDiffFile struct {
	Path      string  `json:"path"`
	OldPath   *string `json:"oldPath,omitempty"`
	Status    string  `json:"status"`
	Staged    bool    `json:"staged"`
	Additions int     `json:"additions"`
	Deletions int     `json:"deletions"`
	Patch     string  `json:"patch"`
	Truncated bool    `json:"truncated"`
}

type TaskInteraction struct {
	ID               string                   `json:"id"`
	TaskID           string                   `json:"taskId"`
	Kind             TaskInteractionKind      `json:"kind"`
	Status           TaskInteractionStatus    `json:"status"`
	Title            string                   `json:"title"`
	Body             string                   `json:"body"`
	RawPayload       string                   `json:"rawPayload"`
	AgentSessionID   *string                  `json:"agentSessionId,omitempty"`
	ResponseDecision *TaskInteractionDecision `json:"responseDecision,omitempty"`
	ResponseMessage  *string                  `json:"responseMessage,omitempty"`
	ResponsePayload  string                   `json:"responsePayload"`
	CreatedAt        time.Time                `json:"createdAt"`
	UpdatedAt        time.Time                `json:"updatedAt"`
}

type TaskLog struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"taskId"`
	Stream    string    `json:"stream"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type TaskReviewComment struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"taskId"`
	Path      string    `json:"path"`
	Line      int       `json:"line"`
	Body      string    `json:"body"`
	Resolved  bool      `json:"resolved"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type TaskReviewFinding struct {
	ID         string                  `json:"id"`
	RunID      string                  `json:"runId"`
	TaskID     string                  `json:"taskId"`
	Path       string                  `json:"path"`
	Line       int                     `json:"line"`
	Severity   TaskReviewSeverity      `json:"severity"`
	Status     TaskReviewFindingStatus `json:"status"`
	Title      string                  `json:"title"`
	Body       string                  `json:"body"`
	Suggestion string                  `json:"suggestion"`
	CreatedAt  time.Time               `json:"createdAt"`
	UpdatedAt  time.Time               `json:"updatedAt"`
}

type TaskReviewRun struct {
	ID          string               `json:"id"`
	TaskID      string               `json:"taskId"`
	Scope       TaskGitDiffScope     `json:"scope"`
	Status      TaskReviewRunStatus  `json:"status"`
	AgentType   *AgentType           `json:"agentType,omitempty"`
	Summary     string               `json:"summary"`
	RawResult   string               `json:"rawResult"`
	Error       string               `json:"error"`
	Findings    []*TaskReviewFinding `json:"findings"`
	StartedAt   *time.Time           `json:"startedAt,omitempty"`
	CompletedAt *time.Time           `json:"completedAt,omitempty"`
	CreatedAt   time.Time            `json:"createdAt"`
	UpdatedAt   time.Time            `json:"updatedAt"`
}

type TaskSortInput struct {
	Field     *TaskSortField `json:"field,omitempty"`
	Direction *SortDirection `json:"direction,omitempty"`
}

type UpdateProjectInput struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	GitURL             string `json:"gitUrl"`
	DefaultBranch      string `json:"defaultBranch"`
	WorktreeNamePrefix string `json:"worktreeNamePrefix"`
}

type UpdateTaskInput struct {
	ID           string     `json:"id"`
	Title        string     `json:"title"`
	Description  *string    `json:"description,omitempty"`
	ProjectID    string     `json:"projectId"`
	AgentType    *AgentType `json:"agentType,omitempty"`
	BaseBranch   *string    `json:"baseBranch,omitempty"`
	PreCommands  []string   `json:"preCommands,omitempty"`
	PostCommands []string   `json:"postCommands,omitempty"`
	StartDate    *time.Time `json:"startDate,omitempty"`
	EndDate      *time.Time `json:"endDate,omitempty"`
}

type UpdateWorkerInput struct {
	ID                 string                        `json:"id"`
	Name               string                        `json:"name"`
	SupportedAgents    []AgentType                   `json:"supportedAgents"`
	WorkDir            string                        `json:"workDir"`
	StartupCommand     *string                       `json:"startupCommand,omitempty"`
	ProjectBindingMode WorkerProjectBindingMode      `json:"projectBindingMode"`
	BoundProjectIds    []string                      `json:"boundProjectIds,omitempty"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnvInput `json:"agentRuntimeEnv,omitempty"`
	Capabilities       []*KeyValueInput              `json:"capabilities,omitempty"`
}

type UpdateWorkerProjectBindingsInput struct {
	WorkerID           string                   `json:"workerId"`
	ProjectBindingMode WorkerProjectBindingMode `json:"projectBindingMode"`
	BoundProjectIds    []string                 `json:"boundProjectIds,omitempty"`
}

type Worker struct {
	ID                 string                   `json:"id"`
	Name               string                   `json:"name"`
	Status             WorkerStatus             `json:"status"`
	Capabilities       []*KeyValue              `json:"capabilities"`
	SupportedAgents    []AgentType              `json:"supportedAgents"`
	WorkDir            string                   `json:"workDir"`
	StartupCommand     *string                  `json:"startupCommand,omitempty"`
	ProjectBindingMode WorkerProjectBindingMode `json:"projectBindingMode"`
	BoundProjectIds    []string                 `json:"boundProjectIds"`
	AgentRuntimeEnv    []*WorkerAgentRuntimeEnv `json:"agentRuntimeEnv"`
	CurrentTaskIds     []string                 `json:"currentTaskIds"`
	LastHeartbeatAt    *time.Time               `json:"lastHeartbeatAt,omitempty"`
	Version            int                      `json:"version"`
	CreatedAt          time.Time                `json:"createdAt"`
	UpdatedAt          time.Time                `json:"updatedAt"`
}

type WorkerAgentRuntimeEnv struct {
	AgentType AgentType             `json:"agentType"`
	Vars      []*AgentRuntimeEnvVar `json:"vars"`
}

type WorkerAgentRuntimeEnvInput struct {
	AgentType AgentType                  `json:"agentType"`
	Vars      []*AgentRuntimeEnvVarInput `json:"vars"`
}

type WorkerConnection struct {
	Nodes      []*Worker `json:"nodes"`
	TotalCount int       `json:"totalCount"`
}

type WorkerFilter struct {
	Status          *WorkerStatus `json:"status,omitempty"`
	ProjectID       *string       `json:"projectId,omitempty"`
	AgentType       *AgentType    `json:"agentType,omitempty"`
	IncludeDisabled *bool         `json:"includeDisabled,omitempty"`
	Search          *string       `json:"search,omitempty"`
}

type WorkerSortInput struct {
	Field     *WorkerSortField `json:"field,omitempty"`
	Direction *SortDirection   `json:"direction,omitempty"`
}

type AgentType string

const (
	AgentTypeCodex  AgentType = "codex"
	AgentTypeClaude AgentType = "claude"
)

var AllAgentType = []AgentType{
	AgentTypeCodex,
	AgentTypeClaude,
}

func (e AgentType) IsValid() bool {
	switch e {
	case AgentTypeCodex, AgentTypeClaude:
		return true
	}
	return false
}

func (e AgentType) String() string {
	return string(e)
}

func (e *AgentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentType", str)
	}
	return nil
}

func (e AgentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentWorkMode string

const (
	AgentWorkModePlan      AgentWorkMode = "PLAN"
	AgentWorkModeImplement AgentWorkMode = "IMPLEMENT"
	AgentWorkModeReview    AgentWorkMode = "REVIEW"
)

var AllAgentWorkMode = []AgentWorkMode{
	AgentWorkModePlan,
	AgentWorkModeImplement,
	AgentWorkModeReview,
}

func (e AgentWorkMode) IsValid() bool {
	switch e {
	case AgentWorkModePlan, AgentWorkModeImplement, AgentWorkModeReview:
		return true
	}
	return false
}

func (e AgentWorkMode) String() string {
	return string(e)
}

func (e *AgentWorkMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentWorkMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentWorkMode", str)
	}
	return nil
}

func (e AgentWorkMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentWorkMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentWorkMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BoardType string

const (
	BoardTypeKanban   BoardType = "KANBAN"
	BoardTypeCalendar BoardType = "CALENDAR"
	BoardTypeList     BoardType = "LIST"
)

var AllBoardType = []BoardType{
	BoardTypeKanban,
	BoardTypeCalendar,
	BoardTypeList,
}

func (e BoardType) IsValid() bool {
	switch e {
	case BoardTypeKanban, BoardTypeCalendar, BoardTypeList:
		return true
	}
	return false
}

func (e BoardType) String() string {
	return string(e)
}

func (e *BoardType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BoardType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BoardType", str)
	}
	return nil
}

func (e BoardType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BoardType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BoardType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ClaudeEffort string

const (
	ClaudeEffortLow    ClaudeEffort = "LOW"
	ClaudeEffortMedium ClaudeEffort = "MEDIUM"
	ClaudeEffortHigh   ClaudeEffort = "HIGH"
	ClaudeEffortXhigh  ClaudeEffort = "XHIGH"
	ClaudeEffortMax    ClaudeEffort = "MAX"
)

var AllClaudeEffort = []ClaudeEffort{
	ClaudeEffortLow,
	ClaudeEffortMedium,
	ClaudeEffortHigh,
	ClaudeEffortXhigh,
	ClaudeEffortMax,
}

func (e ClaudeEffort) IsValid() bool {
	switch e {
	case ClaudeEffortLow, ClaudeEffortMedium, ClaudeEffortHigh, ClaudeEffortXhigh, ClaudeEffortMax:
		return true
	}
	return false
}

func (e ClaudeEffort) String() string {
	return string(e)
}

func (e *ClaudeEffort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClaudeEffort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClaudeEffort", str)
	}
	return nil
}

func (e ClaudeEffort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClaudeEffort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClaudeEffort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ClaudePermissionMode string

const (
	ClaudePermissionModeAcceptEdits       ClaudePermissionMode = "ACCEPT_EDITS"
	ClaudePermissionModeAuto              ClaudePermissionMode = "AUTO"
	ClaudePermissionModeBypassPermissions ClaudePermissionMode = "BYPASS_PERMISSIONS"
	ClaudePermissionModeDefault           ClaudePermissionMode = "DEFAULT"
	ClaudePermissionModeDontAsk           ClaudePermissionMode = "DONT_ASK"
	ClaudePermissionModePlan              ClaudePermissionMode = "PLAN"
)

var AllClaudePermissionMode = []ClaudePermissionMode{
	ClaudePermissionModeAcceptEdits,
	ClaudePermissionModeAuto,
	ClaudePermissionModeBypassPermissions,
	ClaudePermissionModeDefault,
	ClaudePermissionModeDontAsk,
	ClaudePermissionModePlan,
}

func (e ClaudePermissionMode) IsValid() bool {
	switch e {
	case ClaudePermissionModeAcceptEdits, ClaudePermissionModeAuto, ClaudePermissionModeBypassPermissions, ClaudePermissionModeDefault, ClaudePermissionModeDontAsk, ClaudePermissionModePlan:
		return true
	}
	return false
}

func (e ClaudePermissionMode) String() string {
	return string(e)
}

func (e *ClaudePermissionMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClaudePermissionMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClaudePermissionMode", str)
	}
	return nil
}

func (e ClaudePermissionMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClaudePermissionMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClaudePermissionMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CodexApprovalPolicy string

const (
	CodexApprovalPolicyUntrusted CodexApprovalPolicy = "UNTRUSTED"
	CodexApprovalPolicyOnFailure CodexApprovalPolicy = "ON_FAILURE"
	CodexApprovalPolicyOnRequest CodexApprovalPolicy = "ON_REQUEST"
	CodexApprovalPolicyNever     CodexApprovalPolicy = "NEVER"
)

var AllCodexApprovalPolicy = []CodexApprovalPolicy{
	CodexApprovalPolicyUntrusted,
	CodexApprovalPolicyOnFailure,
	CodexApprovalPolicyOnRequest,
	CodexApprovalPolicyNever,
}

func (e CodexApprovalPolicy) IsValid() bool {
	switch e {
	case CodexApprovalPolicyUntrusted, CodexApprovalPolicyOnFailure, CodexApprovalPolicyOnRequest, CodexApprovalPolicyNever:
		return true
	}
	return false
}

func (e CodexApprovalPolicy) String() string {
	return string(e)
}

func (e *CodexApprovalPolicy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CodexApprovalPolicy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CodexApprovalPolicy", str)
	}
	return nil
}

func (e CodexApprovalPolicy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CodexApprovalPolicy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CodexApprovalPolicy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CodexReasoningEffort string

const (
	CodexReasoningEffortMinimal CodexReasoningEffort = "MINIMAL"
	CodexReasoningEffortLow     CodexReasoningEffort = "LOW"
	CodexReasoningEffortMedium  CodexReasoningEffort = "MEDIUM"
	CodexReasoningEffortHigh    CodexReasoningEffort = "HIGH"
	CodexReasoningEffortXhigh   CodexReasoningEffort = "XHIGH"
)

var AllCodexReasoningEffort = []CodexReasoningEffort{
	CodexReasoningEffortMinimal,
	CodexReasoningEffortLow,
	CodexReasoningEffortMedium,
	CodexReasoningEffortHigh,
	CodexReasoningEffortXhigh,
}

func (e CodexReasoningEffort) IsValid() bool {
	switch e {
	case CodexReasoningEffortMinimal, CodexReasoningEffortLow, CodexReasoningEffortMedium, CodexReasoningEffortHigh, CodexReasoningEffortXhigh:
		return true
	}
	return false
}

func (e CodexReasoningEffort) String() string {
	return string(e)
}

func (e *CodexReasoningEffort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CodexReasoningEffort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CodexReasoningEffort", str)
	}
	return nil
}

func (e CodexReasoningEffort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CodexReasoningEffort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CodexReasoningEffort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CodexSandboxMode string

const (
	CodexSandboxModeReadOnly         CodexSandboxMode = "READ_ONLY"
	CodexSandboxModeWorkspaceWrite   CodexSandboxMode = "WORKSPACE_WRITE"
	CodexSandboxModeDangerFullAccess CodexSandboxMode = "DANGER_FULL_ACCESS"
)

var AllCodexSandboxMode = []CodexSandboxMode{
	CodexSandboxModeReadOnly,
	CodexSandboxModeWorkspaceWrite,
	CodexSandboxModeDangerFullAccess,
}

func (e CodexSandboxMode) IsValid() bool {
	switch e {
	case CodexSandboxModeReadOnly, CodexSandboxModeWorkspaceWrite, CodexSandboxModeDangerFullAccess:
		return true
	}
	return false
}

func (e CodexSandboxMode) String() string {
	return string(e)
}

func (e *CodexSandboxMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CodexSandboxMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CodexSandboxMode", str)
	}
	return nil
}

func (e CodexSandboxMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CodexSandboxMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CodexSandboxMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DomainEventSortField string

const (
	DomainEventSortFieldOccurredAt    DomainEventSortField = "OCCURRED_AT"
	DomainEventSortFieldEventType     DomainEventSortField = "EVENT_TYPE"
	DomainEventSortFieldAggregateType DomainEventSortField = "AGGREGATE_TYPE"
	DomainEventSortFieldAggregateID   DomainEventSortField = "AGGREGATE_ID"
)

var AllDomainEventSortField = []DomainEventSortField{
	DomainEventSortFieldOccurredAt,
	DomainEventSortFieldEventType,
	DomainEventSortFieldAggregateType,
	DomainEventSortFieldAggregateID,
}

func (e DomainEventSortField) IsValid() bool {
	switch e {
	case DomainEventSortFieldOccurredAt, DomainEventSortFieldEventType, DomainEventSortFieldAggregateType, DomainEventSortFieldAggregateID:
		return true
	}
	return false
}

func (e DomainEventSortField) String() string {
	return string(e)
}

func (e *DomainEventSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DomainEventSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DomainEventSortField", str)
	}
	return nil
}

func (e DomainEventSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DomainEventSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DomainEventSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectSortField string

const (
	ProjectSortFieldCreatedAt     ProjectSortField = "CREATED_AT"
	ProjectSortFieldUpdatedAt     ProjectSortField = "UPDATED_AT"
	ProjectSortFieldName          ProjectSortField = "NAME"
	ProjectSortFieldGitURL        ProjectSortField = "GIT_URL"
	ProjectSortFieldDefaultBranch ProjectSortField = "DEFAULT_BRANCH"
)

var AllProjectSortField = []ProjectSortField{
	ProjectSortFieldCreatedAt,
	ProjectSortFieldUpdatedAt,
	ProjectSortFieldName,
	ProjectSortFieldGitURL,
	ProjectSortFieldDefaultBranch,
}

func (e ProjectSortField) IsValid() bool {
	switch e {
	case ProjectSortFieldCreatedAt, ProjectSortFieldUpdatedAt, ProjectSortFieldName, ProjectSortFieldGitURL, ProjectSortFieldDefaultBranch:
		return true
	}
	return false
}

func (e ProjectSortField) String() string {
	return string(e)
}

func (e *ProjectSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectSortField", str)
	}
	return nil
}

func (e ProjectSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskGitChangeAction string

const (
	TaskGitChangeActionStage   TaskGitChangeAction = "STAGE"
	TaskGitChangeActionUnstage TaskGitChangeAction = "UNSTAGE"
	TaskGitChangeActionDiscard TaskGitChangeAction = "DISCARD"
	TaskGitChangeActionRestore TaskGitChangeAction = "RESTORE"
)

var AllTaskGitChangeAction = []TaskGitChangeAction{
	TaskGitChangeActionStage,
	TaskGitChangeActionUnstage,
	TaskGitChangeActionDiscard,
	TaskGitChangeActionRestore,
}

func (e TaskGitChangeAction) IsValid() bool {
	switch e {
	case TaskGitChangeActionStage, TaskGitChangeActionUnstage, TaskGitChangeActionDiscard, TaskGitChangeActionRestore:
		return true
	}
	return false
}

func (e TaskGitChangeAction) String() string {
	return string(e)
}

func (e *TaskGitChangeAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskGitChangeAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskGitChangeAction", str)
	}
	return nil
}

func (e TaskGitChangeAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskGitChangeAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskGitChangeAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskGitCommand string

const (
	TaskGitCommandFetch      TaskGitCommand = "FETCH"
	TaskGitCommandPull       TaskGitCommand = "PULL"
	TaskGitCommandRebase     TaskGitCommand = "REBASE"
	TaskGitCommandMergeBase  TaskGitCommand = "MERGE_BASE"
	TaskGitCommandCommit     TaskGitCommand = "COMMIT"
	TaskGitCommandPushBranch TaskGitCommand = "PUSH_BRANCH"
	TaskGitCommandPublish    TaskGitCommand = "PUBLISH"
)

var AllTaskGitCommand = []TaskGitCommand{
	TaskGitCommandFetch,
	TaskGitCommandPull,
	TaskGitCommandRebase,
	TaskGitCommandMergeBase,
	TaskGitCommandCommit,
	TaskGitCommandPushBranch,
	TaskGitCommandPublish,
}

func (e TaskGitCommand) IsValid() bool {
	switch e {
	case TaskGitCommandFetch, TaskGitCommandPull, TaskGitCommandRebase, TaskGitCommandMergeBase, TaskGitCommandCommit, TaskGitCommandPushBranch, TaskGitCommandPublish:
		return true
	}
	return false
}

func (e TaskGitCommand) String() string {
	return string(e)
}

func (e *TaskGitCommand) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskGitCommand(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskGitCommand", str)
	}
	return nil
}

func (e TaskGitCommand) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskGitCommand) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskGitCommand) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskGitDiffScope string

const (
	TaskGitDiffScopeUncommitted TaskGitDiffScope = "UNCOMMITTED"
	TaskGitDiffScopeBranch      TaskGitDiffScope = "BRANCH"
	TaskGitDiffScopeLastTurn    TaskGitDiffScope = "LAST_TURN"
)

var AllTaskGitDiffScope = []TaskGitDiffScope{
	TaskGitDiffScopeUncommitted,
	TaskGitDiffScopeBranch,
	TaskGitDiffScopeLastTurn,
}

func (e TaskGitDiffScope) IsValid() bool {
	switch e {
	case TaskGitDiffScopeUncommitted, TaskGitDiffScopeBranch, TaskGitDiffScopeLastTurn:
		return true
	}
	return false
}

func (e TaskGitDiffScope) String() string {
	return string(e)
}

func (e *TaskGitDiffScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskGitDiffScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskGitDiffScope", str)
	}
	return nil
}

func (e TaskGitDiffScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskGitDiffScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskGitDiffScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskGitPublishStrategy string

const (
	TaskGitPublishStrategyFastForward TaskGitPublishStrategy = "FAST_FORWARD"
	TaskGitPublishStrategyMergeCommit TaskGitPublishStrategy = "MERGE_COMMIT"
)

var AllTaskGitPublishStrategy = []TaskGitPublishStrategy{
	TaskGitPublishStrategyFastForward,
	TaskGitPublishStrategyMergeCommit,
}

func (e TaskGitPublishStrategy) IsValid() bool {
	switch e {
	case TaskGitPublishStrategyFastForward, TaskGitPublishStrategyMergeCommit:
		return true
	}
	return false
}

func (e TaskGitPublishStrategy) String() string {
	return string(e)
}

func (e *TaskGitPublishStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskGitPublishStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskGitPublishStrategy", str)
	}
	return nil
}

func (e TaskGitPublishStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskGitPublishStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskGitPublishStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskInteractionDecision string

const (
	TaskInteractionDecisionApprove           TaskInteractionDecision = "APPROVE"
	TaskInteractionDecisionApproveForSession TaskInteractionDecision = "APPROVE_FOR_SESSION"
	TaskInteractionDecisionDeny              TaskInteractionDecision = "DENY"
	TaskInteractionDecisionCancel            TaskInteractionDecision = "CANCEL"
)

var AllTaskInteractionDecision = []TaskInteractionDecision{
	TaskInteractionDecisionApprove,
	TaskInteractionDecisionApproveForSession,
	TaskInteractionDecisionDeny,
	TaskInteractionDecisionCancel,
}

func (e TaskInteractionDecision) IsValid() bool {
	switch e {
	case TaskInteractionDecisionApprove, TaskInteractionDecisionApproveForSession, TaskInteractionDecisionDeny, TaskInteractionDecisionCancel:
		return true
	}
	return false
}

func (e TaskInteractionDecision) String() string {
	return string(e)
}

func (e *TaskInteractionDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskInteractionDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskInteractionDecision", str)
	}
	return nil
}

func (e TaskInteractionDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskInteractionDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskInteractionDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskInteractionKind string

const (
	TaskInteractionKindUserInput          TaskInteractionKind = "USER_INPUT"
	TaskInteractionKindCommandApproval    TaskInteractionKind = "COMMAND_APPROVAL"
	TaskInteractionKindFileApproval       TaskInteractionKind = "FILE_APPROVAL"
	TaskInteractionKindPermissionApproval TaskInteractionKind = "PERMISSION_APPROVAL"
)

var AllTaskInteractionKind = []TaskInteractionKind{
	TaskInteractionKindUserInput,
	TaskInteractionKindCommandApproval,
	TaskInteractionKindFileApproval,
	TaskInteractionKindPermissionApproval,
}

func (e TaskInteractionKind) IsValid() bool {
	switch e {
	case TaskInteractionKindUserInput, TaskInteractionKindCommandApproval, TaskInteractionKindFileApproval, TaskInteractionKindPermissionApproval:
		return true
	}
	return false
}

func (e TaskInteractionKind) String() string {
	return string(e)
}

func (e *TaskInteractionKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskInteractionKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskInteractionKind", str)
	}
	return nil
}

func (e TaskInteractionKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskInteractionKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskInteractionKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskInteractionStatus string

const (
	TaskInteractionStatusPending  TaskInteractionStatus = "PENDING"
	TaskInteractionStatusAnswered TaskInteractionStatus = "ANSWERED"
	TaskInteractionStatusCanceled TaskInteractionStatus = "CANCELED"
)

var AllTaskInteractionStatus = []TaskInteractionStatus{
	TaskInteractionStatusPending,
	TaskInteractionStatusAnswered,
	TaskInteractionStatusCanceled,
}

func (e TaskInteractionStatus) IsValid() bool {
	switch e {
	case TaskInteractionStatusPending, TaskInteractionStatusAnswered, TaskInteractionStatusCanceled:
		return true
	}
	return false
}

func (e TaskInteractionStatus) String() string {
	return string(e)
}

func (e *TaskInteractionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskInteractionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskInteractionStatus", str)
	}
	return nil
}

func (e TaskInteractionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskInteractionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskInteractionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskReviewFindingStatus string

const (
	TaskReviewFindingStatusOpen      TaskReviewFindingStatus = "OPEN"
	TaskReviewFindingStatusResolved  TaskReviewFindingStatus = "RESOLVED"
	TaskReviewFindingStatusDismissed TaskReviewFindingStatus = "DISMISSED"
)

var AllTaskReviewFindingStatus = []TaskReviewFindingStatus{
	TaskReviewFindingStatusOpen,
	TaskReviewFindingStatusResolved,
	TaskReviewFindingStatusDismissed,
}

func (e TaskReviewFindingStatus) IsValid() bool {
	switch e {
	case TaskReviewFindingStatusOpen, TaskReviewFindingStatusResolved, TaskReviewFindingStatusDismissed:
		return true
	}
	return false
}

func (e TaskReviewFindingStatus) String() string {
	return string(e)
}

func (e *TaskReviewFindingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskReviewFindingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskReviewFindingStatus", str)
	}
	return nil
}

func (e TaskReviewFindingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskReviewFindingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskReviewFindingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskReviewRunStatus string

const (
	TaskReviewRunStatusQueued    TaskReviewRunStatus = "QUEUED"
	TaskReviewRunStatusRunning   TaskReviewRunStatus = "RUNNING"
	TaskReviewRunStatusCompleted TaskReviewRunStatus = "COMPLETED"
	TaskReviewRunStatusFailed    TaskReviewRunStatus = "FAILED"
)

var AllTaskReviewRunStatus = []TaskReviewRunStatus{
	TaskReviewRunStatusQueued,
	TaskReviewRunStatusRunning,
	TaskReviewRunStatusCompleted,
	TaskReviewRunStatusFailed,
}

func (e TaskReviewRunStatus) IsValid() bool {
	switch e {
	case TaskReviewRunStatusQueued, TaskReviewRunStatusRunning, TaskReviewRunStatusCompleted, TaskReviewRunStatusFailed:
		return true
	}
	return false
}

func (e TaskReviewRunStatus) String() string {
	return string(e)
}

func (e *TaskReviewRunStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskReviewRunStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskReviewRunStatus", str)
	}
	return nil
}

func (e TaskReviewRunStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskReviewRunStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskReviewRunStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskReviewSeverity string

const (
	TaskReviewSeverityInfo     TaskReviewSeverity = "INFO"
	TaskReviewSeverityLow      TaskReviewSeverity = "LOW"
	TaskReviewSeverityMedium   TaskReviewSeverity = "MEDIUM"
	TaskReviewSeverityHigh     TaskReviewSeverity = "HIGH"
	TaskReviewSeverityCritical TaskReviewSeverity = "CRITICAL"
)

var AllTaskReviewSeverity = []TaskReviewSeverity{
	TaskReviewSeverityInfo,
	TaskReviewSeverityLow,
	TaskReviewSeverityMedium,
	TaskReviewSeverityHigh,
	TaskReviewSeverityCritical,
}

func (e TaskReviewSeverity) IsValid() bool {
	switch e {
	case TaskReviewSeverityInfo, TaskReviewSeverityLow, TaskReviewSeverityMedium, TaskReviewSeverityHigh, TaskReviewSeverityCritical:
		return true
	}
	return false
}

func (e TaskReviewSeverity) String() string {
	return string(e)
}

func (e *TaskReviewSeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskReviewSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskReviewSeverity", str)
	}
	return nil
}

func (e TaskReviewSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskReviewSeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskReviewSeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskSortField string

const (
	TaskSortFieldCreatedAt TaskSortField = "CREATED_AT"
	TaskSortFieldUpdatedAt TaskSortField = "UPDATED_AT"
	TaskSortFieldTitle     TaskSortField = "TITLE"
	TaskSortFieldStatus    TaskSortField = "STATUS"
	TaskSortFieldStartDate TaskSortField = "START_DATE"
	TaskSortFieldEndDate   TaskSortField = "END_DATE"
)

var AllTaskSortField = []TaskSortField{
	TaskSortFieldCreatedAt,
	TaskSortFieldUpdatedAt,
	TaskSortFieldTitle,
	TaskSortFieldStatus,
	TaskSortFieldStartDate,
	TaskSortFieldEndDate,
}

func (e TaskSortField) IsValid() bool {
	switch e {
	case TaskSortFieldCreatedAt, TaskSortFieldUpdatedAt, TaskSortFieldTitle, TaskSortFieldStatus, TaskSortFieldStartDate, TaskSortFieldEndDate:
		return true
	}
	return false
}

func (e TaskSortField) String() string {
	return string(e)
}

func (e *TaskSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskSortField", str)
	}
	return nil
}

func (e TaskSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusCreated      TaskStatus = "CREATED"
	TaskStatusAssigned     TaskStatus = "ASSIGNED"
	TaskStatusStarting     TaskStatus = "STARTING"
	TaskStatusRunning      TaskStatus = "RUNNING"
	TaskStatusWaitingInput TaskStatus = "WAITING_INPUT"
	TaskStatusInterrupting TaskStatus = "INTERRUPTING"
	TaskStatusInterrupted  TaskStatus = "INTERRUPTED"
	TaskStatusCompleted    TaskStatus = "COMPLETED"
	TaskStatusFailed       TaskStatus = "FAILED"
	TaskStatusArchived     TaskStatus = "ARCHIVED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusCreated,
	TaskStatusAssigned,
	TaskStatusStarting,
	TaskStatusRunning,
	TaskStatusWaitingInput,
	TaskStatusInterrupting,
	TaskStatusInterrupted,
	TaskStatusCompleted,
	TaskStatusFailed,
	TaskStatusArchived,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusCreated, TaskStatusAssigned, TaskStatusStarting, TaskStatusRunning, TaskStatusWaitingInput, TaskStatusInterrupting, TaskStatusInterrupted, TaskStatusCompleted, TaskStatusFailed, TaskStatusArchived:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerProjectBindingMode string

const (
	WorkerProjectBindingModeAllProjects      WorkerProjectBindingMode = "ALL_PROJECTS"
	WorkerProjectBindingModeSpecificProjects WorkerProjectBindingMode = "SPECIFIC_PROJECTS"
)

var AllWorkerProjectBindingMode = []WorkerProjectBindingMode{
	WorkerProjectBindingModeAllProjects,
	WorkerProjectBindingModeSpecificProjects,
}

func (e WorkerProjectBindingMode) IsValid() bool {
	switch e {
	case WorkerProjectBindingModeAllProjects, WorkerProjectBindingModeSpecificProjects:
		return true
	}
	return false
}

func (e WorkerProjectBindingMode) String() string {
	return string(e)
}

func (e *WorkerProjectBindingMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerProjectBindingMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerProjectBindingMode", str)
	}
	return nil
}

func (e WorkerProjectBindingMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerProjectBindingMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerProjectBindingMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerSortField string

const (
	WorkerSortFieldCreatedAt       WorkerSortField = "CREATED_AT"
	WorkerSortFieldUpdatedAt       WorkerSortField = "UPDATED_AT"
	WorkerSortFieldName            WorkerSortField = "NAME"
	WorkerSortFieldStatus          WorkerSortField = "STATUS"
	WorkerSortFieldLastHeartbeatAt WorkerSortField = "LAST_HEARTBEAT_AT"
)

var AllWorkerSortField = []WorkerSortField{
	WorkerSortFieldCreatedAt,
	WorkerSortFieldUpdatedAt,
	WorkerSortFieldName,
	WorkerSortFieldStatus,
	WorkerSortFieldLastHeartbeatAt,
}

func (e WorkerSortField) IsValid() bool {
	switch e {
	case WorkerSortFieldCreatedAt, WorkerSortFieldUpdatedAt, WorkerSortFieldName, WorkerSortFieldStatus, WorkerSortFieldLastHeartbeatAt:
		return true
	}
	return false
}

func (e WorkerSortField) String() string {
	return string(e)
}

func (e *WorkerSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerSortField", str)
	}
	return nil
}

func (e WorkerSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerStatus string

const (
	WorkerStatusRegistered WorkerStatus = "REGISTERED"
	WorkerStatusOnline     WorkerStatus = "ONLINE"
	WorkerStatusOffline    WorkerStatus = "OFFLINE"
	WorkerStatusError      WorkerStatus = "ERROR"
	WorkerStatusDisabled   WorkerStatus = "DISABLED"
)

var AllWorkerStatus = []WorkerStatus{
	WorkerStatusRegistered,
	WorkerStatusOnline,
	WorkerStatusOffline,
	WorkerStatusError,
	WorkerStatusDisabled,
}

func (e WorkerStatus) IsValid() bool {
	switch e {
	case WorkerStatusRegistered, WorkerStatusOnline, WorkerStatusOffline, WorkerStatusError, WorkerStatusDisabled:
		return true
	}
	return false
}

func (e WorkerStatus) String() string {
	return string(e)
}

func (e *WorkerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerStatus", str)
	}
	return nil
}

func (e WorkerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
