package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/tangxusc/block-play-table/manager/internal/app"
	"github.com/tangxusc/block-play-table/manager/internal/graph/model"
	"github.com/tangxusc/block-play-table/pkg/domain"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	task, err := r.Service.CreateTask(ctx, app.CreateTaskInput{
		Title:        input.Title,
		Description:  valueOrEmpty(input.Description),
		ProjectID:    input.ProjectID,
		AgentType:    domain.AgentType(input.AgentType),
		BaseBranch:   valueOrEmpty(input.BaseBranch),
		TargetBranch: valueOrEmpty(input.TargetBranch),
		PreCommands:  append([]string(nil), input.PreCommands...),
		PostCommands: append([]string(nil), input.PostCommands...),
	})
	return toModelTask(task), err
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, input model.UpdateTaskInput) (*model.Task, error) {
	task, err := r.Service.UpdateTask(ctx, app.UpdateTaskInput{
		ID:           input.ID,
		Title:        input.Title,
		Description:  valueOrEmpty(input.Description),
		ProjectID:    input.ProjectID,
		AgentType:    domain.AgentType(input.AgentType),
		BaseBranch:   valueOrEmpty(input.BaseBranch),
		TargetBranch: valueOrEmpty(input.TargetBranch),
		PreCommands:  append([]string(nil), input.PreCommands...),
		PostCommands: append([]string(nil), input.PostCommands...),
	})
	return toModelTask(task), err
}

// AssignWorker is the resolver for the assignWorker field.
func (r *mutationResolver) AssignWorker(ctx context.Context, input *model.AssignWorkerInput, taskID *string, workerID *string) (*model.Task, error) {
	if input != nil {
		taskID = &input.TaskID
		workerID = &input.WorkerID
	}
	if taskID == nil || workerID == nil {
		return nil, fmt.Errorf("taskId and workerId are required")
	}
	task, err := r.Service.AssignWorker(ctx, *taskID, *workerID)
	return toModelTask(task), err
}

// StartTask is the resolver for the startTask field.
func (r *mutationResolver) StartTask(ctx context.Context, input *model.StartTaskInput, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if input != nil {
		resolvedTaskID = input.TaskID
	}
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, payload, err := r.Service.StartTask(ctx, resolvedTaskID)
	if err != nil {
		return nil, err
	}
	if r.WorkerSender != nil {
		if err := r.WorkerSender.SendTaskStart(task.WorkerID, task.ID, payload); err != nil {
			_, _ = r.Service.ApplyWorkerTaskFailed(ctx, "delivery-failed-"+task.ID, task.ID, "task start delivery failed: "+err.Error())
			return nil, err
		}
	}
	return toModelTask(task), nil
}

// InterruptTask is the resolver for the interruptTask field.
func (r *mutationResolver) InterruptTask(ctx context.Context, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, workerID, err := r.Service.InterruptTask(ctx, resolvedTaskID)
	if err != nil {
		return nil, err
	}
	if r.WorkerSender != nil {
		if err := r.WorkerSender.SendTaskInterrupt(workerID, resolvedTaskID); err != nil {
			_, _ = r.Service.ApplyWorkerTaskInterrupted(ctx, "interrupt-delivery-failed-"+task.ID, task.ID, "interrupt delivery failed: "+err.Error())
			return nil, err
		}
	}
	return toModelTask(task), nil
}

// ArchiveTask is the resolver for the archiveTask field.
func (r *mutationResolver) ArchiveTask(ctx context.Context, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, err := r.Service.ArchiveTask(ctx, resolvedTaskID)
	return toModelTask(task), err
}

// RetryTask is the resolver for the retryTask field.
func (r *mutationResolver) RetryTask(ctx context.Context, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, err := r.Service.RetryTask(ctx, resolvedTaskID)
	return toModelTask(task), err
}

// CreateWorker is the resolver for the createWorker field.
func (r *mutationResolver) CreateWorker(ctx context.Context, input model.CreateWorkerInput) (*model.Worker, error) {
	return r.registerWorkerFromInput(ctx, input.ID, input.Name, input.SupportedAgents, input.WorkDir, input.StartupCommand, input.ProjectBindingMode, input.BoundProjectIds, input.Capabilities, true)
}

// RegisterWorker is the resolver for the registerWorker field.
func (r *mutationResolver) RegisterWorker(ctx context.Context, input model.RegisterWorkerInput) (*model.Worker, error) {
	return r.registerWorkerFromInput(ctx, input.ID, input.Name, input.SupportedAgents, input.WorkDir, input.StartupCommand, input.ProjectBindingMode, input.BoundProjectIds, input.Capabilities, true)
}

// UpdateWorker is the resolver for the updateWorker field.
func (r *mutationResolver) UpdateWorker(ctx context.Context, input model.UpdateWorkerInput) (*model.Worker, error) {
	worker, err := r.Service.UpdateWorker(ctx, app.RegisterWorkerInput{
		ID:              input.ID,
		Name:            input.Name,
		SupportedAgents: domainAgents(input.SupportedAgents),
		WorkDir:         input.WorkDir,
		StartupCommand:  valueOrEmpty(input.StartupCommand),
		BindingMode:     domain.WorkerProjectBindingMode(input.ProjectBindingMode),
		BoundProjectIDs: append([]string(nil), input.BoundProjectIds...),
		Capabilities:    fromKeyValueInputs(input.Capabilities),
	})
	return toModelWorker(worker), err
}

// UpdateWorkerProjectBindings is the resolver for the updateWorkerProjectBindings field.
func (r *mutationResolver) UpdateWorkerProjectBindings(ctx context.Context, input model.UpdateWorkerProjectBindingsInput) (*model.Worker, error) {
	worker, err := r.Service.UpdateWorkerProjectBindings(ctx, input.WorkerID, domain.WorkerProjectBindingMode(input.ProjectBindingMode), input.BoundProjectIds)
	return toModelWorker(worker), err
}

// EnableWorker is the resolver for the enableWorker field.
func (r *mutationResolver) EnableWorker(ctx context.Context, id string) (*model.Worker, error) {
	worker, err := r.Service.EnableWorker(ctx, id)
	return toModelWorker(worker), err
}

// DisableWorker is the resolver for the disableWorker field.
func (r *mutationResolver) DisableWorker(ctx context.Context, id string) (*model.Worker, error) {
	worker, err := r.Service.DisableWorker(ctx, id)
	return toModelWorker(worker), err
}

// DeleteWorker is the resolver for the deleteWorker field.
func (r *mutationResolver) DeleteWorker(ctx context.Context, id string) (bool, error) {
	if err := r.Service.DeleteWorker(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	project, err := r.Service.CreateProject(ctx, app.CreateProjectInput{
		Name:               input.Name,
		GitURL:             input.GitURL,
		DefaultBranch:      valueOrEmpty(input.DefaultBranch),
		WorktreeNamePrefix: valueOrEmpty(input.WorktreeNamePrefix),
	})
	return toModelProject(project), err
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, input model.UpdateProjectInput) (*model.Project, error) {
	project, err := r.Service.UpdateProject(ctx, app.UpdateProjectInput{
		ID:                 input.ID,
		Name:               input.Name,
		GitURL:             input.GitURL,
		DefaultBranch:      input.DefaultBranch,
		WorktreeNamePrefix: input.WorktreeNamePrefix,
	})
	return toModelProject(project), err
}

// ArchiveProject is the resolver for the archiveProject field.
func (r *mutationResolver) ArchiveProject(ctx context.Context, id string) (*model.Project, error) {
	project, err := r.Service.ArchiveProject(ctx, id)
	return toModelProject(project), err
}

// UpdateAgentRuntimeEnvVars is the resolver for the updateAgentRuntimeEnvVars field.
func (r *mutationResolver) UpdateAgentRuntimeEnvVars(ctx context.Context, input model.UpdateAgentRuntimeEnvVarsInput) (*model.Settings, error) {
	vars := make([]domain.AgentRuntimeEnvVar, 0, len(input.Vars))
	for _, item := range input.Vars {
		if item == nil {
			continue
		}
		vars = append(vars, domain.AgentRuntimeEnvVar{
			Key:         item.Key,
			Value:       valueOrEmpty(item.Value),
			Description: valueOrEmpty(item.Description),
			Enabled:     item.Enabled,
			Sensitive:   item.Sensitive,
		})
	}
	settings, err := r.Service.UpdateAgentRuntimeEnvVars(ctx, vars)
	return toModelSettings(settings), err
}

// UpdateWorkerHeartbeatTimeout is the resolver for the updateWorkerHeartbeatTimeout field.
func (r *mutationResolver) UpdateWorkerHeartbeatTimeout(ctx context.Context, timeout string) (*model.Settings, error) {
	settings, err := r.Service.UpdateWorkerHeartbeatTimeout(ctx, timeout)
	return toModelSettings(settings), err
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.Service.Task(ctx, id)
	if err != nil {
		return nil, err
	}
	return toModelTask(task), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, filter *model.TaskFilter, page *model.PageInput) (*model.TaskConnection, error) {
	tasks, total, err := r.Service.TasksFiltered(ctx, taskFilter(filter), pageInput(page))
	if err != nil {
		return nil, err
	}
	return &model.TaskConnection{Nodes: toModelTasks(tasks), TotalCount: total}, nil
}

// TaskList is the resolver for the taskList field.
func (r *queryResolver) TaskList(ctx context.Context, filter *model.TaskFilter, page *model.PageInput) ([]*model.Task, error) {
	tasks, _, err := r.Service.TasksFiltered(ctx, taskFilter(filter), pageInput(page))
	return toModelTasks(tasks), err
}

// Worker is the resolver for the worker field.
func (r *queryResolver) Worker(ctx context.Context, id string) (*model.Worker, error) {
	worker, err := r.Service.Worker(ctx, id)
	if err != nil {
		return nil, err
	}
	return toModelWorker(worker), nil
}

// Workers is the resolver for the workers field.
func (r *queryResolver) Workers(ctx context.Context, filter *model.WorkerFilter) ([]*model.Worker, error) {
	workers, err := r.Service.WorkersFiltered(ctx, workerFilter(filter))
	return toModelWorkers(workers), err
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	project, err := r.Service.Project(ctx, id)
	if err != nil {
		return nil, err
	}
	return toModelProject(project), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, filter *model.ProjectFilter) ([]*model.Project, error) {
	includeArchived := false
	if filter != nil && filter.IncludeArchived != nil {
		includeArchived = *filter.IncludeArchived
	}
	projects, err := r.Service.ProjectsFiltered(ctx, includeArchived)
	return toModelProjects(projects), err
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id *string) (*model.Board, error) {
	tasks, _, err := r.Service.TasksFiltered(ctx, app.TaskFilter{IncludeArchived: true}, app.PageInput{})
	if err != nil {
		return nil, err
	}
	boardType := model.BoardTypeKanban
	name := "Default Board"
	boardID := "default"
	if id != nil && *id != "" {
		boardID = *id
		switch *id {
		case "calendar":
			boardType = model.BoardTypeCalendar
			name = "Calendar"
		case "list":
			boardType = model.BoardTypeList
			name = "List"
		}
	}
	columns := boardColumns(tasks)
	calendarItems := make([]*model.BoardCalendarItem, 0, len(tasks))
	for _, task := range tasks {
		calendarItems = append(calendarItems, &model.BoardCalendarItem{ID: task.ID, Task: toModelTask(task), Date: task.CreatedAt, Status: model.TaskStatus(task.Status)})
	}
	return &model.Board{ID: boardID, Name: name, Type: boardType, Columns: columns, CalendarItems: calendarItems, Tasks: toModelTasks(tasks)}, nil
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*model.Settings, error) {
	settings, err := r.Service.Settings(ctx)
	return toModelSettings(settings), err
}

// TaskEvents is the resolver for the taskEvents field.
func (r *queryResolver) TaskEvents(ctx context.Context, taskID string) ([]*model.DomainEvent, error) {
	events, err := r.Service.DomainEvents(ctx, domain.EventFilter{AggregateID: taskID})
	return toModelEvents(events), err
}

// DomainEvents is the resolver for the domainEvents field.
func (r *queryResolver) DomainEvents(ctx context.Context, filter *model.DomainEventFilter, aggregateID *string, aggregateType *string, eventType *string) ([]*model.DomainEvent, error) {
	domainFilter := eventFilter(filter)
	if aggregateID != nil {
		domainFilter.AggregateID = *aggregateID
	}
	if aggregateType != nil {
		domainFilter.AggregateType = *aggregateType
	}
	if eventType != nil {
		domainFilter.EventType = *eventType
	}
	events, err := r.Service.DomainEvents(ctx, domainFilter)
	return toModelEvents(events), err
}

// OutboxMessages is the resolver for the outboxMessages field.
func (r *queryResolver) OutboxMessages(ctx context.Context, includePublished *bool) ([]*model.OutboxMessage, error) {
	include := true
	if includePublished != nil {
		include = *includePublished
	}
	messages, err := r.Service.OutboxMessages(ctx, include)
	if err != nil {
		return nil, err
	}
	out := make([]*model.OutboxMessage, 0, len(messages))
	for _, message := range messages {
		out = append(out, toModelOutbox(message))
	}
	return out, nil
}

// TaskLogs is the resolver for the taskLogs field.
func (r *queryResolver) TaskLogs(ctx context.Context, taskID string) ([]*model.TaskLog, error) {
	logs, err := r.Service.Store().TaskLogs(ctx, taskID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.TaskLog, 0, len(logs))
	for _, log := range logs {
		out = append(out, toModelTaskLog(log))
	}
	return out, nil
}

// TaskConversations is the resolver for the taskConversations field.
func (r *queryResolver) TaskConversations(ctx context.Context, taskID string) ([]*model.ConversationMessage, error) {
	messages, err := r.Service.Store().TaskConversations(ctx, taskID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ConversationMessage, 0, len(messages))
	for _, message := range messages {
		out = append(out, toModelConversation(message))
	}
	return out, nil
}

// TaskUpdated is the resolver for the taskUpdated field.
func (r *subscriptionResolver) TaskUpdated(ctx context.Context, taskID string) (<-chan *model.DomainEvent, error) {
	return subscribeEvents(ctx, r.Service, domain.EventFilter{AggregateID: taskID, AggregateType: "Task"}), nil
}

// TaskLogAppended is the resolver for the taskLogAppended field.
func (r *subscriptionResolver) TaskLogAppended(ctx context.Context, taskID string) (<-chan *model.TaskLog, error) {
	events := subscribeRawEvents(ctx, r.Service, domain.EventFilter{AggregateID: taskID, AggregateType: "Task", EventType: "TaskLogAppended"})
	out := make(chan *model.TaskLog, 64)
	go func() {
		defer close(out)
		for event := range events {
			log := &model.TaskLog{ID: event.EventID, TaskID: taskID, Stream: eventPayloadString(event, "stream"), Content: eventPayloadString(event, "content"), CreatedAt: event.OccurredAt}
			select {
			case out <- log:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// TaskConversationAppended is the resolver for the taskConversationAppended field.
func (r *subscriptionResolver) TaskConversationAppended(ctx context.Context, taskID string) (<-chan *model.ConversationMessage, error) {
	events := subscribeRawEvents(ctx, r.Service, domain.EventFilter{AggregateID: taskID, AggregateType: "Task", EventType: "TaskConversationAppended"})
	out := make(chan *model.ConversationMessage, 64)
	go func() {
		defer close(out)
		for event := range events {
			message := &model.ConversationMessage{ID: event.EventID, TaskID: taskID, Role: eventPayloadString(event, "role"), Content: eventPayloadString(event, "content"), CreatedAt: event.OccurredAt}
			if message.Role == "" {
				message.Role = "assistant"
			}
			select {
			case out <- message:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// WorkerUpdated is the resolver for the workerUpdated field.
func (r *subscriptionResolver) WorkerUpdated(ctx context.Context, workerID *string) (<-chan *model.DomainEvent, error) {
	filter := domain.EventFilter{AggregateType: "Worker"}
	if workerID != nil {
		filter.AggregateID = *workerID
	}
	return subscribeEvents(ctx, r.Service, filter), nil
}

// DomainEvents is the resolver for the domainEvents field.
func (r *subscriptionResolver) DomainEvents(ctx context.Context, filter *model.DomainEventFilter) (<-chan *model.DomainEvent, error) {
	return subscribeEvents(ctx, r.Service, eventFilter(filter)), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
