package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/tangxusc/block-play-table/manager/internal/app"
	"github.com/tangxusc/block-play-table/manager/internal/graph/model"
	"github.com/tangxusc/block-play-table/pkg/domain"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	var agentType domain.AgentType
	if input.AgentType != nil {
		agentType = domain.AgentType(*input.AgentType)
	}
	var startDate time.Time
	if input.StartDate != nil {
		startDate = *input.StartDate
	}
	var endDate time.Time
	if input.EndDate != nil {
		endDate = *input.EndDate
	}
	task, err := r.Service.CreateTask(ctx, app.CreateTaskInput{
		Title:        input.Title,
		Description:  valueOrEmpty(input.Description),
		ProjectID:    input.ProjectID,
		WorkerID:     valueOrEmpty(input.WorkerID),
		AgentType:    agentType,
		AgentConfig:  fromAgentExecutionConfigInput(input.AgentConfig),
		BaseBranch:   valueOrEmpty(input.BaseBranch),
		PreCommands:  append([]string(nil), input.PreCommands...),
		PostCommands: append([]string(nil), input.PostCommands...),
		StartDate:    startDate,
		EndDate:      endDate,
	})
	return toModelTask(task), err
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, input model.UpdateTaskInput) (*model.Task, error) {
	var agentType domain.AgentType
	if input.AgentType != nil {
		agentType = domain.AgentType(*input.AgentType)
	}
	var startDate time.Time
	if input.StartDate != nil {
		startDate = *input.StartDate
	}
	var endDate time.Time
	if input.EndDate != nil {
		endDate = *input.EndDate
	}
	task, err := r.Service.UpdateTask(ctx, app.UpdateTaskInput{
		ID:           input.ID,
		Title:        input.Title,
		Description:  valueOrEmpty(input.Description),
		ProjectID:    input.ProjectID,
		AgentType:    agentType,
		BaseBranch:   valueOrEmpty(input.BaseBranch),
		PreCommands:  append([]string(nil), input.PreCommands...),
		PostCommands: append([]string(nil), input.PostCommands...),
		StartDate:    startDate,
		EndDate:      endDate,
	})
	return toModelTask(task), err
}

// AssignWorker is the resolver for the assignWorker field.
func (r *mutationResolver) AssignWorker(ctx context.Context, input *model.AssignWorkerInput, taskID *string, workerID *string) (*model.Task, error) {
	if input != nil {
		taskID = &input.TaskID
		workerID = &input.WorkerID
	}
	if taskID == nil || workerID == nil {
		return nil, fmt.Errorf("taskId and workerId are required")
	}
	var agentTypes []domain.AgentType
	if input != nil && input.AgentType != nil {
		agentTypes = append(agentTypes, domain.AgentType(*input.AgentType))
	}
	var config *domain.AgentExecutionConfig
	if input != nil {
		config = fromAgentExecutionConfigInput(input.AgentConfig)
	}
	task, err := r.Service.AssignWorkerWithConfig(ctx, *taskID, *workerID, config, agentTypes...)
	return toModelTask(task), err
}

// StartTask is the resolver for the startTask field.
func (r *mutationResolver) StartTask(ctx context.Context, input *model.StartTaskInput, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if input != nil {
		resolvedTaskID = input.TaskID
	}
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, payload, err := r.Service.StartTask(ctx, resolvedTaskID)
	if err != nil {
		return nil, err
	}
	if r.WorkerSender != nil {
		if err := r.WorkerSender.SendTaskStart(task.WorkerID, task.ID, payload); err != nil {
			_, _ = r.Service.ApplyWorkerTaskFailed(ctx, "delivery-failed-"+task.ID, task.ID, "task start delivery failed: "+err.Error())
			return nil, err
		}
	}
	return toModelTask(task), nil
}

// ContinueTask is the resolver for the continueTask field.
func (r *mutationResolver) ContinueTask(ctx context.Context, input model.ContinueTaskInput) (*model.Task, error) {
	task, payload, err := r.Service.ContinueTask(ctx, app.ContinueTaskInput{
		TaskID:  input.TaskID,
		Message: input.Message,
	})
	if err != nil {
		return nil, err
	}
	if r.WorkerSender != nil {
		if err := r.WorkerSender.SendTaskContinue(task.WorkerID, task.ID, payload); err != nil {
			_, _ = r.Service.ApplyWorkerTaskFailed(ctx, "continue-delivery-failed-"+task.ID, task.ID, "task continue delivery failed: "+err.Error())
			return nil, err
		}
	}
	return toModelTask(task), nil
}

// RespondTaskInteraction is the resolver for the respondTaskInteraction field.
func (r *mutationResolver) RespondTaskInteraction(ctx context.Context, input model.RespondTaskInteractionInput) (*model.TaskInteraction, error) {
	decision := domain.TaskInteractionDecision("")
	if input.Decision != nil {
		decision = domain.TaskInteractionDecision(*input.Decision)
	}
	task, _, payload, err := r.Service.PrepareTaskInteractionResponse(ctx, app.RespondTaskInteractionInput{
		InteractionID: input.InteractionID,
		Decision:      decision,
		Message:       valueOrEmpty(input.Message),
		Payload:       valueOrEmpty(input.Payload),
	})
	if err != nil {
		return nil, err
	}
	if r.WorkerSender == nil {
		return nil, fmt.Errorf("worker sender is not configured")
	}
	if err := r.WorkerSender.SendTaskInteractionResponse(task.WorkerID, task.ID, payload); err != nil {
		return nil, err
	}
	interaction, err := r.Service.MarkTaskInteractionAnswered(ctx, app.RespondTaskInteractionInput{
		InteractionID: input.InteractionID,
		Decision:      decision,
		Message:       valueOrEmpty(input.Message),
		Payload:       valueOrEmpty(input.Payload),
	})
	if err != nil {
		return nil, err
	}
	return toModelTaskInteraction(interaction), nil
}

// InterruptTask is the resolver for the interruptTask field.
func (r *mutationResolver) InterruptTask(ctx context.Context, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, workerID, err := r.Service.InterruptTask(ctx, resolvedTaskID)
	if err != nil {
		return nil, err
	}
	if r.WorkerSender != nil {
		if err := r.WorkerSender.SendTaskInterrupt(workerID, resolvedTaskID); err != nil {
			_, _ = r.Service.ApplyWorkerTaskInterrupted(ctx, "interrupt-delivery-failed-"+task.ID, task.ID, "interrupt delivery failed: "+err.Error())
			return nil, err
		}
	}
	return toModelTask(task), nil
}

// ArchiveTask is the resolver for the archiveTask field.
func (r *mutationResolver) ArchiveTask(ctx context.Context, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, err := r.Service.ArchiveTask(ctx, resolvedTaskID)
	return toModelTask(task), err
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, taskID *string, id *string) (bool, error) {
	resolvedTaskID := firstID(taskID, id)
	if resolvedTaskID == "" {
		return false, fmt.Errorf("taskId is required")
	}
	if err := r.Service.DeleteTask(ctx, resolvedTaskID); err != nil {
		return false, err
	}
	return true, nil
}

// RetryTask is the resolver for the retryTask field.
func (r *mutationResolver) RetryTask(ctx context.Context, taskID *string, id *string) (*model.Task, error) {
	resolvedTaskID := firstID(taskID, id)
	if resolvedTaskID == "" {
		return nil, fmt.Errorf("taskId is required")
	}
	task, err := r.Service.RetryTask(ctx, resolvedTaskID)
	return toModelTask(task), err
}

// StageTaskGitChanges is the resolver for the stageTaskGitChanges field.
func (r *mutationResolver) StageTaskGitChanges(ctx context.Context, input model.TaskGitChangeInput) (*model.TaskGitChangeResult, error) {
	return r.gitChange(ctx, "stage", input)
}

// UnstageTaskGitChanges is the resolver for the unstageTaskGitChanges field.
func (r *mutationResolver) UnstageTaskGitChanges(ctx context.Context, input model.TaskGitChangeInput) (*model.TaskGitChangeResult, error) {
	return r.gitChange(ctx, "unstage", input)
}

// DiscardTaskGitChanges is the resolver for the discardTaskGitChanges field.
func (r *mutationResolver) DiscardTaskGitChanges(ctx context.Context, input model.TaskGitChangeInput) (*model.TaskGitChangeResult, error) {
	return r.gitChange(ctx, "discard", input)
}

// RestoreTaskGitBackup is the resolver for the restoreTaskGitBackup field.
func (r *mutationResolver) RestoreTaskGitBackup(ctx context.Context, input model.TaskGitChangeInput) (*model.TaskGitChangeResult, error) {
	return r.gitChange(ctx, "restore", input)
}

// RunTaskGitCommand is the resolver for the runTaskGitCommand field.
func (r *mutationResolver) RunTaskGitCommand(ctx context.Context, input model.TaskGitCommandInput) (*model.TaskGitCommandResult, error) {
	return r.runTaskGitCommand(ctx, input)
}

// CreateWorker is the resolver for the createWorker field.
func (r *mutationResolver) CreateWorker(ctx context.Context, input model.CreateWorkerInput) (*model.Worker, error) {
	return r.registerWorkerFromInput(ctx, input.ID, input.Name, input.SupportedAgents, input.WorkDir, input.StartupCommand, input.ProjectBindingMode, input.BoundProjectIds, input.AgentRuntimeEnv, input.Capabilities, true)
}

// RegisterWorker is the resolver for the registerWorker field.
func (r *mutationResolver) RegisterWorker(ctx context.Context, input model.RegisterWorkerInput) (*model.Worker, error) {
	return r.registerWorkerFromInput(ctx, input.ID, input.Name, input.SupportedAgents, input.WorkDir, input.StartupCommand, input.ProjectBindingMode, input.BoundProjectIds, input.AgentRuntimeEnv, input.Capabilities, true)
}

// UpdateWorker is the resolver for the updateWorker field.
func (r *mutationResolver) UpdateWorker(ctx context.Context, input model.UpdateWorkerInput) (*model.Worker, error) {
	worker, err := r.Service.UpdateWorker(ctx, app.RegisterWorkerInput{
		ID:                     input.ID,
		Name:                   input.Name,
		SupportedAgents:        domainAgents(input.SupportedAgents),
		WorkDir:                input.WorkDir,
		StartupCommand:         valueOrEmpty(input.StartupCommand),
		BindingMode:            domain.WorkerProjectBindingMode(input.ProjectBindingMode),
		BoundProjectIDs:        append([]string(nil), input.BoundProjectIds...),
		AgentRuntimeEnv:        fromWorkerAgentRuntimeEnvInputs(input.AgentRuntimeEnv),
		ReplaceAgentRuntimeEnv: true,
		Capabilities:           fromKeyValueInputs(input.Capabilities),
	})
	return toModelWorker(worker), err
}

// UpdateWorkerProjectBindings is the resolver for the updateWorkerProjectBindings field.
func (r *mutationResolver) UpdateWorkerProjectBindings(ctx context.Context, input model.UpdateWorkerProjectBindingsInput) (*model.Worker, error) {
	worker, err := r.Service.UpdateWorkerProjectBindings(ctx, input.WorkerID, domain.WorkerProjectBindingMode(input.ProjectBindingMode), input.BoundProjectIds)
	return toModelWorker(worker), err
}

// EnableWorker is the resolver for the enableWorker field.
func (r *mutationResolver) EnableWorker(ctx context.Context, id string) (*model.Worker, error) {
	worker, err := r.Service.EnableWorker(ctx, id)
	return toModelWorker(worker), err
}

// DisableWorker is the resolver for the disableWorker field.
func (r *mutationResolver) DisableWorker(ctx context.Context, id string) (*model.Worker, error) {
	worker, err := r.Service.DisableWorker(ctx, id)
	return toModelWorker(worker), err
}

// DeleteWorker is the resolver for the deleteWorker field.
func (r *mutationResolver) DeleteWorker(ctx context.Context, id string) (bool, error) {
	if err := r.Service.DeleteWorker(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	project, err := r.Service.CreateProject(ctx, app.CreateProjectInput{
		Name:               input.Name,
		GitURL:             input.GitURL,
		DefaultBranch:      valueOrEmpty(input.DefaultBranch),
		WorktreeNamePrefix: valueOrEmpty(input.WorktreeNamePrefix),
	})
	return toModelProject(project), err
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, input model.UpdateProjectInput) (*model.Project, error) {
	project, err := r.Service.UpdateProject(ctx, app.UpdateProjectInput{
		ID:                 input.ID,
		Name:               input.Name,
		GitURL:             input.GitURL,
		DefaultBranch:      input.DefaultBranch,
		WorktreeNamePrefix: input.WorktreeNamePrefix,
	})
	return toModelProject(project), err
}

// ArchiveProject is the resolver for the archiveProject field.
func (r *mutationResolver) ArchiveProject(ctx context.Context, id string) (*model.Project, error) {
	project, err := r.Service.ArchiveProject(ctx, id)
	return toModelProject(project), err
}

// UpdateWorkerHeartbeatTimeout is the resolver for the updateWorkerHeartbeatTimeout field.
func (r *mutationResolver) UpdateWorkerHeartbeatTimeout(ctx context.Context, timeout string) (*model.Settings, error) {
	settings, err := r.Service.UpdateWorkerHeartbeatTimeout(ctx, timeout)
	return toModelSettings(settings), err
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.Service.Task(ctx, id)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return toModelTask(task), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, filter *model.TaskFilter, sort *model.TaskSortInput, page *model.PageInput) (*model.TaskConnection, error) {
	tasks, total, err := r.Service.TasksFilteredSorted(ctx, taskFilter(filter), taskSort(sort), pageInput(page))
	if err != nil {
		return nil, err
	}
	return &model.TaskConnection{Nodes: toModelTasks(tasks), TotalCount: total}, nil
}

// TaskList is the resolver for the taskList field.
func (r *queryResolver) TaskList(ctx context.Context, filter *model.TaskFilter, sort *model.TaskSortInput, page *model.PageInput) ([]*model.Task, error) {
	tasks, _, err := r.Service.TasksFilteredSorted(ctx, taskFilter(filter), taskSort(sort), pageInput(page))
	return toModelTasks(tasks), err
}

// Worker is the resolver for the worker field.
func (r *queryResolver) Worker(ctx context.Context, id string) (*model.Worker, error) {
	worker, err := r.Service.Worker(ctx, id)
	if err != nil {
		return nil, err
	}
	return toModelWorker(worker), nil
}

// Workers is the resolver for the workers field.
func (r *queryResolver) Workers(ctx context.Context, filter *model.WorkerFilter, sort *model.WorkerSortInput) ([]*model.Worker, error) {
	workers, err := r.Service.WorkersFilteredSorted(ctx, workerFilter(filter), workerSort(sort))
	return toModelWorkers(workers), err
}

// WorkersConnection is the resolver for the workersConnection field.
func (r *queryResolver) WorkersConnection(ctx context.Context, filter *model.WorkerFilter, sort *model.WorkerSortInput, page *model.PageInput) (*model.WorkerConnection, error) {
	workers, total, err := r.Service.WorkersFilteredPageSorted(ctx, workerFilter(filter), workerSort(sort), pageInput(page))
	if err != nil {
		return nil, err
	}
	return &model.WorkerConnection{Nodes: toModelWorkers(workers), TotalCount: total}, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	project, err := r.Service.Project(ctx, id)
	if err != nil {
		return nil, err
	}
	return toModelProject(project), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, filter *model.ProjectFilter, sort *model.ProjectSortInput) ([]*model.Project, error) {
	projects, err := r.Service.ProjectsFilteredSorted(ctx, projectFilter(filter), projectSort(sort))
	return toModelProjects(projects), err
}

// ProjectsConnection is the resolver for the projectsConnection field.
func (r *queryResolver) ProjectsConnection(ctx context.Context, filter *model.ProjectFilter, sort *model.ProjectSortInput, page *model.PageInput) (*model.ProjectConnection, error) {
	projects, total, err := r.Service.ProjectsFilteredPageSorted(ctx, projectFilter(filter), projectSort(sort), pageInput(page))
	if err != nil {
		return nil, err
	}
	return &model.ProjectConnection{Nodes: toModelProjects(projects), TotalCount: total}, nil
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id *string, filter *model.TaskFilter, sort *model.TaskSortInput, page *model.PageInput) (*model.Board, error) {
	boardFilter := taskFilter(filter)
	tasks, total, err := r.Service.TasksFilteredSorted(ctx, boardFilter, taskSort(sort), pageInput(page))
	if err != nil {
		return nil, err
	}
	boardType := model.BoardTypeKanban
	name := "Default Board"
	boardID := "default"
	if id != nil && *id != "" {
		boardID = *id
		switch *id {
		case "calendar":
			boardType = model.BoardTypeCalendar
			name = "Calendar"
		case "list":
			boardType = model.BoardTypeList
			name = "List"
		}
	}
	columns := boardColumns(tasks)
	calendarItems := make([]*model.BoardCalendarItem, 0, len(tasks))
	for _, task := range tasks {
		modelTask := toModelTask(task)
		calendarItems = append(calendarItems, &model.BoardCalendarItem{ID: task.ID, Task: modelTask, Date: modelTask.StartDate, Status: model.TaskStatus(task.Status)})
	}
	return &model.Board{ID: boardID, Name: name, Type: boardType, TotalCount: total, Columns: columns, CalendarItems: calendarItems, Tasks: toModelTasks(tasks)}, nil
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*model.Settings, error) {
	settings, err := r.Service.Settings(ctx)
	return toModelSettings(settings), err
}

// TaskEvents is the resolver for the taskEvents field.
func (r *queryResolver) TaskEvents(ctx context.Context, taskID string) ([]*model.DomainEvent, error) {
	events, err := r.Service.DomainEvents(ctx, domain.EventFilter{AggregateID: taskID})
	return toModelEvents(events), err
}

// DomainEvents is the resolver for the domainEvents field.
func (r *queryResolver) DomainEvents(ctx context.Context, filter *model.DomainEventFilter, sort *model.DomainEventSortInput, aggregateID *string, aggregateType *string, eventType *string) ([]*model.DomainEvent, error) {
	domainFilter := eventFilter(filter)
	if aggregateID != nil {
		domainFilter.AggregateID = *aggregateID
	}
	if aggregateType != nil {
		domainFilter.AggregateType = *aggregateType
	}
	if eventType != nil {
		domainFilter.EventType = *eventType
	}
	events, err := r.Service.DomainEventsSorted(ctx, domainFilter, domainEventSort(sort))
	return toModelEvents(events), err
}

// DomainEventsConnection is the resolver for the domainEventsConnection field.
func (r *queryResolver) DomainEventsConnection(ctx context.Context, filter *model.DomainEventFilter, sort *model.DomainEventSortInput, aggregateID *string, aggregateType *string, eventType *string, page *model.PageInput) (*model.DomainEventConnection, error) {
	domainFilter := eventFilter(filter)
	if aggregateID != nil {
		domainFilter.AggregateID = *aggregateID
	}
	if aggregateType != nil {
		domainFilter.AggregateType = *aggregateType
	}
	if eventType != nil {
		domainFilter.EventType = *eventType
	}
	events, total, err := r.Service.DomainEventsPageSorted(ctx, domainFilter, domainEventSort(sort), pageInput(page))
	if err != nil {
		return nil, err
	}
	return &model.DomainEventConnection{Nodes: toModelEvents(events), TotalCount: total}, nil
}

// OutboxMessages is the resolver for the outboxMessages field.
func (r *queryResolver) OutboxMessages(ctx context.Context, includePublished *bool) ([]*model.OutboxMessage, error) {
	include := true
	if includePublished != nil {
		include = *includePublished
	}
	messages, err := r.Service.OutboxMessages(ctx, include)
	if err != nil {
		return nil, err
	}
	out := make([]*model.OutboxMessage, 0, len(messages))
	for _, message := range messages {
		out = append(out, toModelOutbox(message))
	}
	return out, nil
}

// TaskLogs is the resolver for the taskLogs field.
func (r *queryResolver) TaskLogs(ctx context.Context, taskID string) ([]*model.TaskLog, error) {
	logs, err := r.Service.Store().TaskLogs(ctx, taskID)
	if err != nil {
		return nil, err
	}
	if len(logs) == 0 {
		messages, err := r.Service.Store().TaskConversations(ctx, taskID)
		if err != nil {
			return nil, err
		}
		out := make([]*model.TaskLog, 0, len(messages))
		for _, message := range messages {
			out = append(out, &model.TaskLog{
				ID:        message.ID,
				TaskID:    message.TaskID,
				Stream:    message.Role,
				Content:   message.Content,
				CreatedAt: message.CreatedAt,
			})
		}
		return out, nil
	}
	out := make([]*model.TaskLog, 0, len(logs))
	for _, log := range logs {
		out = append(out, toModelTaskLog(log))
	}
	return out, nil
}

// TaskConversations is the resolver for the taskConversations field.
func (r *queryResolver) TaskConversations(ctx context.Context, taskID string) ([]*model.ConversationMessage, error) {
	messages, err := r.Service.Store().TaskConversations(ctx, taskID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ConversationMessage, 0, len(messages))
	for _, message := range messages {
		out = append(out, toModelConversation(message))
	}
	return out, nil
}

// TaskInteractions is the resolver for the taskInteractions field.
func (r *queryResolver) TaskInteractions(ctx context.Context, taskID string, status *model.TaskInteractionStatus) ([]*model.TaskInteraction, error) {
	filter := domain.TaskInteractionStatus("")
	if status != nil {
		filter = domain.TaskInteractionStatus(*status)
	}
	interactions, err := r.Service.Store().TaskInteractions(ctx, taskID, filter)
	if err != nil {
		return nil, err
	}
	return toModelTaskInteractions(interactions), nil
}

// TaskGitDiff is the resolver for the taskGitDiff field.
func (r *queryResolver) TaskGitDiff(ctx context.Context, taskID string, scope model.TaskGitDiffScope, staged *bool) (*model.TaskGitDiff, error) {
	return r.taskGitDiff(ctx, taskID, scope, staged)
}

// TaskGitStatus is the resolver for the taskGitStatus field.
func (r *queryResolver) TaskGitStatus(ctx context.Context, taskID string, remote *string, branch *string) (*model.TaskGitStatus, error) {
	return r.taskGitStatus(ctx, taskID, remote, branch)
}

// TaskGitBackups is the resolver for the taskGitBackups field.
func (r *queryResolver) TaskGitBackups(ctx context.Context, taskID string) ([]*model.TaskGitBackup, error) {
	backups, err := r.Service.Store().TaskGitBackups(ctx, taskID)
	if err != nil {
		return nil, err
	}
	return toModelTaskGitBackups(backups), nil
}

// TaskUpdated is the resolver for the taskUpdated field.
func (r *subscriptionResolver) TaskUpdated(ctx context.Context, taskID string) (<-chan *model.DomainEvent, error) {
	return subscribeEvents(ctx, r.Service, domain.EventFilter{AggregateID: taskID, AggregateType: "Task"}), nil
}

// TaskLogAppended is the resolver for the taskLogAppended field.
func (r *subscriptionResolver) TaskLogAppended(ctx context.Context, taskID string) (<-chan *model.TaskLog, error) {
	events := subscribeRawEvents(ctx, r.Service, domain.EventFilter{AggregateID: taskID, AggregateType: "Task", EventType: "TaskLogAppended"})
	out := make(chan *model.TaskLog, 64)
	go func() {
		defer close(out)
		for event := range events {
			log := &model.TaskLog{ID: event.EventID, TaskID: taskID, Stream: eventPayloadString(event, "stream"), Content: eventPayloadString(event, "content"), CreatedAt: event.OccurredAt}
			select {
			case out <- log:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// TaskConversationAppended is the resolver for the taskConversationAppended field.
func (r *subscriptionResolver) TaskConversationAppended(ctx context.Context, taskID string) (<-chan *model.ConversationMessage, error) {
	events := subscribeRawEvents(ctx, r.Service, domain.EventFilter{AggregateID: taskID, AggregateType: "Task", EventType: "TaskConversationAppended"})
	out := make(chan *model.ConversationMessage, 64)
	go func() {
		defer close(out)
		for event := range events {
			message := &model.ConversationMessage{ID: event.EventID, TaskID: taskID, Role: eventPayloadString(event, "role"), Content: eventPayloadString(event, "content"), CreatedAt: event.OccurredAt}
			if message.Role == "" {
				message.Role = "assistant"
			}
			select {
			case out <- message:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// WorkerUpdated is the resolver for the workerUpdated field.
func (r *subscriptionResolver) WorkerUpdated(ctx context.Context, workerID *string) (<-chan *model.DomainEvent, error) {
	filter := domain.EventFilter{AggregateType: "Worker"}
	if workerID != nil {
		filter.AggregateID = *workerID
	}
	return subscribeEvents(ctx, r.Service, filter), nil
}

// DomainEvents is the resolver for the domainEvents field.
func (r *subscriptionResolver) DomainEvents(ctx context.Context, filter *model.DomainEventFilter) (<-chan *model.DomainEvent, error) {
	return subscribeEvents(ctx, r.Service, eventFilter(filter)), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
