#!/usr/bin/env bash

set -euo pipefail

readonly GOBCO_VERSION="1.3.4"
readonly DEFAULT_THRESHOLD="80"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
go_bin="${GO:-go}"
tool_dir="${repo_root}/.tools/bin"
gobco_bin="${tool_dir}/gobco"
cache_dir="${repo_root}/.gocache"
gopath_dir="${repo_root}/.gopath"
report_dir="${repo_root}/.coverage/go-branch"
threshold="${GO_BRANCH_THRESHOLD:-${DEFAULT_THRESHOLD}}"
stats_bin="${tool_dir}/gobco-stats"
shadow_dir=""

export GOCACHE="${GOCACHE:-${cache_dir}}"
export GOPATH="${GOPATH:-${gopath_dir}}"
export GOMODCACHE="${GOMODCACHE:-${gopath_dir}/pkg/mod}"

cleanup_shadow() {
  if [[ -n "${shadow_dir}" && -d "${shadow_dir}" ]]; then
    rm -rf -- "${shadow_dir}"
  fi
}

trap cleanup_shadow EXIT INT TERM

meets_threshold() {
  local covered="$1"
  local total="$2"
  local required="$3"
  awk -v covered="${covered}" -v total="${total}" -v required="${required}" '
    BEGIN {
      if (total == 0) exit 2
      exit !((covered * 100.0 / total) + 0.0000001 >= required)
    }
  '
}

is_generated_file() {
  local file="$1"
  if command -v rg >/dev/null 2>&1; then
    rg -q '^// Code generated .* DO NOT EDIT\.$' "${file}"
  else
    grep -Eq '^// Code generated .* DO NOT EDIT\.$' "${file}"
  fi
}

self_test() {
  local fixture
  local excluded
  local generated_fixture
  local handwritten_fixture
  local counts
  fixture="$(mktemp "${TMPDIR:-/tmp}/bpt-gobco-self-test.XXXXXX.json")"
  excluded="$(mktemp "${TMPDIR:-/tmp}/bpt-gobco-excluded.XXXXXX.txt")"
  generated_fixture="$(mktemp "${TMPDIR:-/tmp}/bpt-gobco-generated.XXXXXX.go")"
  handwritten_fixture="$(mktemp "${TMPDIR:-/tmp}/bpt-gobco-handwritten.XXXXXX.go")"
  trap "rm -f '${fixture}' '${excluded}' '${generated_fixture}' '${handwritten_fixture}'" EXIT

  printf '[{"Start":"pkg/main.go:1:1","Code":"condition","TrueCount":1,"FalseCount":0},{"Start":"pkg/main.go:1:1","Code":"condition","TrueCount":0,"FalseCount":1},{"Start":"pkg/generated.go:2:1","Code":"generated","TrueCount":0,"FalseCount":0},{"Start":"other/main.go:3:1","Code":"other","TrueCount":0,"FalseCount":0}]\n' > "${fixture}"
  printf 'pkg/generated.go\n' > "${excluded}"
  printf '// Code generated by self-test, DO NOT EDIT.\n\npackage fixture\n' > "${generated_fixture}"
  printf 'package fixture\n' > "${handwritten_fixture}"
  mkdir -p "${tool_dir}" "${GOCACHE}" "${GOMODCACHE}"
  "${go_bin}" build -o "${stats_bin}" "${repo_root}/scripts/gobco_stats.go"
  if ! is_generated_file "${generated_fixture}"; then
    printf '分支覆盖率自检未识别标准 Go 生成标记\n' >&2
    return 1
  fi
  if is_generated_file "${handwritten_fixture}"; then
    printf '分支覆盖率自检把手写文件识别为生成文件\n' >&2
    return 1
  fi
  counts="$(${stats_bin} "${fixture}" "${excluded}")"
  [[ "${counts}" == "2 4" ]]
  counts="$(${stats_bin} "${fixture}" "${excluded}" pkg)"
  [[ "${counts}" == "2 2" ]]
  meets_threshold 8 10 80
  if meets_threshold 7 10 80; then
    printf '分支覆盖率自检未识别低于阈值的结果\n' >&2
    return 1
  fi
  if meets_threshold 0 0 80; then
    printf '分支覆盖率自检未识别零分母\n' >&2
    return 1
  else
    [[ "$?" -eq 2 ]]
  fi
  printf 'invalid\n' > "${fixture}"
  if "${stats_bin}" "${fixture}" "${excluded}" >/dev/null 2>&1; then
    printf '分支覆盖率自检接受了无效 JSON\n' >&2
    return 1
  fi
  printf 'gobco 输出解析、阈值和零分母自检通过\n'
}

ensure_gobco() {
  local installed=""
  if [[ -x "${gobco_bin}" ]]; then
    installed="$(${gobco_bin} -version 2>/dev/null || true)"
  fi
  if [[ "${installed}" == "${GOBCO_VERSION}" ]]; then
    return
  fi

  mkdir -p "${tool_dir}" "${GOCACHE}" "${GOMODCACHE}"
  printf '安装 gobco v%s 到 %s\n' "${GOBCO_VERSION}" "${gobco_bin}"
  GOBIN="${tool_dir}" "${go_bin}" install "github.com/rillig/gobco@v${GOBCO_VERSION}"
  installed="$(${gobco_bin} -version)"
  if [[ "${installed}" != "${GOBCO_VERSION}" ]]; then
    printf 'gobco 版本不匹配：期望 %s，实际 %s\n' "${GOBCO_VERSION}" "${installed}" >&2
    return 1
  fi
}

run_gobco() {
  local target="$1"
  local log_file="$2"
  local stats_file="$3"
  local module_root="$4"
  local test_pattern="$5"
  if ! (cd "${module_root}" && "${gobco_bin}" -branch -stats "${stats_file}" -test=-count=1 -test=-p=1 -test="${test_pattern}" "${target}") > "${log_file}" 2>&1; then
    cat "${log_file}" >&2
    return 1
  fi
  cat "${log_file}"
}

prepare_shadow() {
  local package_file="$1"
  shadow_dir="$(mktemp -d "${TMPDIR:-/tmp}/bpt-gobco-shadow.XXXXXX")"
  cp "${repo_root}/go.mod" "${repo_root}/go.sum" "${shadow_dir}/"
  cp -R "${repo_root}/manager" "${repo_root}/worker" "${repo_root}/pkg" "${shadow_dir}/"

  while IFS='|' read -r _ package_dir _ ignored_csv; do
    [[ -n "${package_dir}" && -n "${ignored_csv}" ]] || continue
    local relative_dir="${package_dir#${repo_root}/}"
    local ignored=()
    local file
    IFS=',' read -r -a ignored <<< "${ignored_csv}"
    for file in "${ignored[@]}"; do
      [[ -n "${file}" ]] || continue
      # gobco v1.3.4 类型检查会忽略 build tag，这里只修改隔离副本以避免跨平台符号重定义。
      rm -f -- "${shadow_dir}/${relative_dir}/${file}"
    done
  done < "${package_file}"
}

count_test_packages() {
  local module_root="$1"
  local pattern="$2"
  local count=0
  local _
  while IFS= read -r _; do
    count=$((count + 1))
  done < <(cd "${module_root}" && "${go_bin}" list "${pattern}")
  printf '%s' "${count}"
}

main() {
  if [[ "${1:-}" == "--self-test" ]]; then
    self_test
    return
  fi
  if [[ "$#" -ne 0 ]]; then
    printf '用法：%s [--self-test]\n' "$0" >&2
    return 2
  fi

  ensure_gobco
  mkdir -p "${report_dir}" "${GOCACHE}" "${GOMODCACHE}"
  "${go_bin}" build -o "${stats_bin}" "${repo_root}/scripts/gobco_stats.go"
  local package_file="${report_dir}/packages.txt"
  local report_file="${report_dir}/report.tsv"
  local patterns
  local global_covered=0
  local global_total=0
  local counted_packages=0
  local skipped_packages=0

  patterns="${GO_BRANCH_PACKAGES:-./manager/... ./worker/... ./pkg/...}"
  # 此处有意按空白拆分，包模式本身不能包含空白。
  # shellcheck disable=SC2086
  "${go_bin}" list -f '{{.ImportPath}}|{{.Dir}}|{{join .GoFiles ","}}|{{join .IgnoredGoFiles ","}}' ${patterns} > "${package_file}"
  prepare_shadow "${package_file}"
  local manager_run_count
  local worker_run_count
  local all_run_count
  manager_run_count="$(count_test_packages "${shadow_dir}" 'github.com/tangxusc/block-play-table/manager/...')"
  worker_run_count="$(count_test_packages "${shadow_dir}" 'github.com/tangxusc/block-play-table/worker/...')"
  all_run_count="$(count_test_packages "${shadow_dir}" 'github.com/tangxusc/block-play-table/...')"
  printf 'package\tcovered\ttotal\tpercent\truns\n' > "${report_file}"

  while IFS='|' read -r import_path package_dir files_csv _; do
    [[ -n "${import_path}" ]] || continue
    local handwritten=()
    local generated=()
    local go_files=()
    local file
    IFS=',' read -r -a go_files <<< "${files_csv}"
    for file in "${go_files[@]}"; do
      [[ -n "${file}" ]] || continue
      if is_generated_file "${package_dir}/${file}"; then
        generated+=("${file}")
      else
        handwritten+=("${file}")
      fi
    done

    if [[ "${#handwritten[@]}" -eq 0 ]]; then
      printf '跳过 %s：没有手写生产 Go 文件\n' "${import_path}"
      skipped_packages=$((skipped_packages + 1))
      continue
    fi

    local package_covered=0
    local package_total=0
    local test_pattern
    local run_count
    case "${import_path}" in
      */manager/*)
        test_pattern="github.com/tangxusc/block-play-table/manager/..."
        run_count="${manager_run_count}"
        ;;
      */worker/*)
        test_pattern="github.com/tangxusc/block-play-table/worker/..."
        run_count="${worker_run_count}"
        ;;
      */pkg/*)
        test_pattern="github.com/tangxusc/block-play-table/..."
        run_count="${all_run_count}"
        ;;
      *)
        printf '无法确定 %s 的测试组\n' "${import_path}" >&2
        return 1
        ;;
    esac
    local safe_name
    safe_name="$(printf '%s' "${import_path}" | tr '/.' '__')"
    local target="./${package_dir#${repo_root}/}"
    local log_file="${report_dir}/${safe_name}.log"
    local stats_file="${report_dir}/${safe_name}.stats.json"
    local excluded_file="${report_dir}/${safe_name}.generated.txt"
    : > "${excluded_file}"
    for file in "${generated[@]}"; do
      printf '%s/%s\n' "${package_dir#${repo_root}/}" "${file}" >> "${excluded_file}"
    done
    rm -f "${stats_file}"
    printf '\n[%s] gobco 插桩 %s，并串行运行测试组 %s（%s 个包）\n' "${import_path}" "${target}" "${test_pattern}" "${run_count}"
    run_gobco "${target}" "${log_file}" "${stats_file}" "${shadow_dir}" "${test_pattern}"
    local counts
    counts="$(${stats_bin} "${stats_file}" "${excluded_file}" "${package_dir#${repo_root}/}")"
    package_covered="${counts%% *}"
    package_total="${counts##* }"

    if [[ "${package_total}" -eq 0 ]]; then
      printf '跳过 %s：gobco 分支分母为 0\n' "${import_path}"
      printf '%s\t0\t0\tN/A\t%s\n' "${import_path}" "${run_count}" >> "${report_file}"
      skipped_packages=$((skipped_packages + 1))
      continue
    fi

    local percent
    percent="$(awk -v covered="${package_covered}" -v total="${package_total}" 'BEGIN { printf "%.2f", covered * 100.0 / total }')"
    printf '%s\t%s\t%s\t%s%%\t%s\n' "${import_path}" "${package_covered}" "${package_total}" "${percent}" "${run_count}" >> "${report_file}"
    printf '%s：%s/%s (%s%%)\n' "${import_path}" "${package_covered}" "${package_total}" "${percent}"
    global_covered=$((global_covered + package_covered))
    global_total=$((global_total + package_total))
    counted_packages=$((counted_packages + 1))
  done < "${package_file}"

  if [[ "${global_total}" -eq 0 ]]; then
    printf '未发现可统计的 gobco 分支\n' >&2
    return 1
  fi
  local global_percent
  global_percent="$(awk -v covered="${global_covered}" -v total="${global_total}" 'BEGIN { printf "%.2f", covered * 100.0 / total }')"
  printf 'TOTAL\t%s\t%s\t%s%%\t%s packages, %s skipped\n' \
    "${global_covered}" "${global_total}" "${global_percent}" "${counted_packages}" "${skipped_packages}" >> "${report_file}"
  printf '\nGo 手写生产代码 gobco 分支覆盖率：%s/%s (%s%%)，阈值 %s%%\n' \
    "${global_covered}" "${global_total}" "${global_percent}" "${threshold}"

  if ! meets_threshold "${global_covered}" "${global_total}" "${threshold}"; then
    printf 'Go 分支覆盖率 %s%% 低于 %s%%；报告：%s\n' "${global_percent}" "${threshold}" "${report_file}" >&2
    return 1
  fi
}

main "$@"
